### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by chrnie** [NicolasGuilloux/blade-shadow-beta#11]
Fullscreen is lctrl+lshift+f
Toggle input grab is lctrl+lshift+g

Possible solutions:

- fix output in wrapper.pl
- change shortcuts

**Comment by NicolasGuilloux** [comment]
I updated the wrapper with the commit 862745ac7c1b5f20016b328f78848b32266b2314 and it fixed the shortcuts. Thanks ! ;)
