### ISSUE TITLE
Keyboard shortcuts ignore keyboard layout

### ISSUE THREAD

**Issue by Niid** [NicolasGuilloux/blade-shadow-beta#14]
**Describe the bug**
The keyboard shortcuts aren't synced with the keyboard layout

**System**
 - OS: Ubuntu (should happen on all
 - OS Version: 18.04
 - Environment: Budgie
 - Application: AppImage
 - Application Version: 2.0.2

**Configuration**
 - The user is in input group ? yes
 - The environment uses Xorg ? yes
 - VA API detects H264 ? And H265 ? h264 only

**To Reproduce**
1 - change keyboard layout to qwerty
2 - launch Shadow (and the stream)
3 - try ctrl+shift+q
4 - nothing happens
5 - try ctrl+shift+a
6 - the stream closes.

**Additional context**
QWERTY keyboard layout

**Comment by DelphicOkami** [comment]
I can confirm the above, I'm glad Niid pointed this out or I would have restarted my machine to close Shadow

**Comment by MouhK** [comment]
Hellom

This issue is fixed and will be deploy in the next version

Thanks

**Comment by aarnoud** [comment]
fixed in 4.1.10+ release
