### ISSUE TITLE
Controllers buttons misplaced

### ISSUE THREAD

**Issue by Niid** [NicolasGuilloux/blade-shadow-beta#15]
**Describe the bug**
Some controller buttons are not mapped to the right actions or behave weirdly:
- dpad up  and dpad down are reversed
- RB works ... Sometimes ... And sometimes it acts like dpad down(depending of the game and menu somehow... in FH4 it seems to act as rb+dpad down in the car list, in MHW it acts like rb in some menus and dpad down in others like the start menu)

**System**
 - OS: Ubuntu
 - OS Version: e.g. 18.04
 - Environment: Budgie
 - Application: AppImage and .deb
 - Application Version: 2.0.2

**Configuration**
 - The user is in input group ? yes
 - The environment uses Xorg ? yes
 - VA API detects H264 ? And H265 ? h264 only

**To Reproduce**
1. Start a game
2. Press dpad down
3. watch the selector go up
4. enjoy

**Additional context**
Happens with a genuine Xbox One S Bluetooth controller (Which is picked up as an xbox 360 controller by Windows, not sure if that's normal), and according to a member of Shadow USA, happens with a genuine Xbox 360 wired controller too.

**Comment by digitalcowpie** [comment]
I can confirm that this happens with a genuine xbox 360 wired controller too on Elementary OS 5.0. Any update on this issue, can we help? I can speak French if necessary.

**Comment by aarnoud** [comment]
it's known and not yet fixed, it's part of work of the re-work of game controller in unified client.

**Comment by digitalcowpie** [comment]
Thank you for the answer. I'd like to point out that the liquidsky service has/had the exact same issue, down to the actual controller mapping :
https://community.liquidsky.tv/t/xbox-360-wireles-contorler-analog-problems/23674/23 
https://community.liquidsky.tv/t/xbox-one-controller-has-mismaped-buttons-and-inverted-axis/27644/6

Only difference is : it affected their windows app. I guess you are using the same software. Some liquidsky users tinkered with a joystick.ini file to solve or, more likely, mitigate the problem so... I understand you are working on it, but in the meantime, is there a linux file responsible for controller input mapping that we can edit to try to alleviate the issue on our own ? I'm not asking for the keys to the shop here, just some pointers. If you can't I'll totally understand. 

Anyhow, good luck @MouhK.

**Comment by MouhK** [comment]
Hello,

The problem has been fixed and will be deploy in the next release.

Thank you

**Comment by digitalcowpie** [comment]
Thank you @MouhK, I really appreciate it.

**Comment by aarnoud** [comment]
available in latest version
