### ISSUE TITLE
Please do not zip AppImage

### ISSUE THREAD

**Issue by probonopd** [NicolasGuilloux/blade-shadow-beta#16]
On https://nicolasguilloux.github.io/blade-shadow-beta/#appimage an AppImage is available for download. Great! :+1: 

Please don't zip it or put it into another archive, because it reduces the functionality. For more information please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake.

**Comment by aarnoud** [comment]
Hi, indeed, this form is transitional and made for convenience for now, we are working on something for this :) thanks for your feedback !
