### ISSUE TITLE
Debian Install Script Fails With 404

### ISSUE THREAD

**Issue by wakearray** [NicolasGuilloux/blade-shadow-beta#17]
*Describe the bug**
**Debian install script fails with 404 when attempting to download .deb package: 
https://macosx.update.blade-group.fr/mpl/linux/beta/artful/shadowbeta.deb**

**System**
 - OS: **Debian**
 - OS Version: **9.5**
 - Environment: **Gnome**
 - Application: **.deb**
 - Application Version: **Unsure**

**Configuration**
 - The user is in input group ? **Yes**
 - The environment uses Xorg ? **Yes**
 - VA API detects H264 ? And H265 ? **H264 and H265**

**To Reproduce**
1. **Download install_debain.sh from 
https://github.com/NicolasGuilloux/blade-shadow-beta/blob/master/Debian/install_debian.sh**
2. **Run script as super user.**
3. **Receive error: 
_"Download the deb file
--2018-11-03 20:32:23--  https://macosx.update.blade-group.fr/mpl/linux/beta/artful/shadowbeta.deb
Resolving macosx.update.blade-group.fr (macosx.update.blade-group.fr)... 146.185.149.42
Connecting to macosx.update.blade-group.fr (macosx.update.blade-group.fr)|146.185.149.42|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-11-03 20:32:24 ERROR 404: Not Found."**_

**Screenshots**
**N/A**

**Additional context**
**N/A**

**Comment by aarnoud** [comment]
Hi, those scripts have been deprecated with latest delivery from Blade, we've requested dev team, to provide an ubuntu 16.04 release so we can make an appImage that will work for almost all distributions. On Debian you can either upgrade to testing (newer glibc) and use AppImage or wait until they deliver.

**Comment by wakearray** [comment]
Gotcha. Thanks for letting me know. I set up a persistent Debian Buster weekly alpha on a USB drive and after a little bit of fiddling, I was able to get the AppImage to work. My only issue is with the scroll wheel working in the opposite direction. Pretty minor issue all things considered. 👍

**Comment by NicolasGuilloux** [comment]
I will warn the user that the scripts are deprecated in most cases.
If you want to build one, you can add a pull request or talk to us on Discord :)
