### ISSUE TITLE
[FEATURE] Improve issues with automatic data gathering

### ISSUE THREAD

**Issue by avallete** [NicolasGuilloux/blade-shadow-beta#18]
Hi everyone,

Today trying to open an issue. I asked myself, which kind of data could be useful to help quickly identificate the problem.

So, started a little list of the things who could be useful for a shadow application bug report:

```
# Get information about the system version/type
uname -a
# Get computer global hardware infos
 lshw -short
# Get informations about computer installed packages often required to make shadow work
dpkg --list | grep -E '(vainfo|libva)'
# Get informations about the user (check if he is into the input group)
groups
# Get information about PCI devices
lspci -v
vainfo
# Get informations about graphical environment
env | grep XDG_
# Get back the Shadow application logs
cat ~/.local/Shadow\ Beta/log.log
```

Of course, it's only a draft. But, this kind of structured way to gather informations could be scripted and added to the `ISSUE.md`.

**Comment by NicolasGuilloux** [comment]
Hello !

Thanks for contributing to this project :)
About the feature you asked, an option is available with the `wrapper.pl` (linked with `report.pl`) and with the Shadow Debug Tool. It creates a cleaned report with useful information about the computer. 
I let you check the following link: https://github.com/NicolasGuilloux/blade-shadow-beta/blob/master/AppImage/report.pl

The `wrapper.pl` and `report.pl` combined, they check:
- `vainfo` and create cases based on its result
- the environment used
- if the user is in the `input` group
- all dependancies
- the logs

You can quickly generate a report by typing `./wrapper.pl --report`, starting directly `./report.pl` or, with the AppImage `./shadowbeta-linux-x86_64.AppImage --report`.
It will provide a link so you can share it easily . Be careful, the link is temporary, so if you need to share it to a Github issue, please copy the content and paste it between three ` characters.

However, I will consider a small tutorial put in `ISSUE.md` like you suggested to help people understand and make the debugging by themselves ;)
