### ISSUE TITLE
Environment detection by the wrapper failed (once)

### ISSUE THREAD

**Issue by Kabouik** [NicolasGuilloux/blade-shadow-beta#2]
I used the AppImage on an Live USB with Ubuntu 18.04 and Xorg, but was notified on the first launch that I was not using Xorg. The error said something along those lines:

`Your environnement is not Xorg but is identified as`

Note that no environment was detailed at the end of the sentence, probably simply because the wrapper failed to detect my environment, and hence threw the error in the first place. 

The error was gone after running the application another time, and it [ran correctly](http://reho.st/0x0.st/sJY2.png), so I'm not sure what caused the issue. The screenshot also gives additional details about the machine and drivers I used, if relevant for troubleshooting.

**Comment by avallete** [comment]
Got the same error today, for me the problem was that I had launched the program in a terminal logged as root.

Logging back to my normal user make it work fine.

I suspect some missing variables into the `env` for some users (as the one who have no home like root) to be the cause of the error.

@Kabouik can you confirm that you experienced the same error when logged as 'default' user ?

**Comment by NicolasGuilloux** [comment]
Thanks !
Yes you should not start the script as root because Shadow is designed to use a regular user and store everything in his folder. I will probably change the wrapper to stop if the AppImage is started with root rights.

**Comment by Kabouik** [comment]
This is something I forgot to mention in the first post and now, to be honest, I don't remember. My bad.

I cannot exclude that I did run the application as root to circumvent the `input` group membership issue. I was using a Live distribution with no persistence, and therefore had no way to add `$USER` to `input` and then restart the session with these changes. In that case, running the application as root might be the only way to use it on a Live distribution. I don't think doing so would be a corner case at all, as one may want to use Shadow from any other computer when on the go, including those with no administrator rights (hence the need of a Live USB), so I am not sure how beneficial it would be in the end to just prevent it.

**Comment by NicolasGuilloux** [comment]
I do not have any USB key available to test it right now, but can someone just try to execute the command `env` and then `sudo env` ?
On my Arch Linux, I don't have any issue whether I use my user or the root user with user. However, when I log into the console as root (`sudo su`), it doesn't work anymore.

I will block the script if somebody start it as root. But I hear you Kabouik, I will try to find a solution to add the user to the "input" group without restarting the session. I will be more convenient.

But on a Live installation, you just have to log out and log in again right ? You can't do that ? It's not a reboot, so the memory won't be flushed right ?

**Comment by Kabouik** [comment]
I don't have any Live USB at hand here, sorry.

You make a good point about the memory being flushed or not, I'm not sure actually. This would need some testing.
