### ISSUE TITLE
Keyboard and Mouse input not working

### ISSUE THREAD

**Issue by jreichert** [NicolasGuilloux/blade-shadow-beta#21]
I am able to connect to my Shadow and see the running Win10 instance, but I can't interact with it.  It does not recognize any key presses or mouse clicks..  When running in windowed mode the mouse is constrained to the Shadow window, and because the keys don't work I can't exit the program. Keyboard shortcuts don't work to kill the app, so the only way to exit is to hold down the power button on the computer until it hard reboots.

Here is the app report:
https://nicolasguilloux.eu/hostbin/1774572822

**System**
 - OS: GalliumOS
 - OS Version: 3.0
 - Application: AppImage
 - Application Version: whatever the latest is - I downloaded it today

**Configuration**
 - The user is in input group ? yes
 - The environment uses Xorg ? Not sure - Shadow tools says "impossible to know if I am using Xorg".
 - VA API detects H264 ? And H265 ? yes

**To Reproduce**
1. run the AppImage
2. log in
3. connect to my Shadow
4. mouse pointer is constrained to my Shadow desktop but it won't register any mouse clicks or key presses

**Comment by aarnoud** [comment]
Hi, thanks for your feedback, is this issue still exists, did you reboot in between tests ?

**Comment by jreichert** [comment]
I'm assuming your question is if I rebooted my Shadow, not if I rebooted my laptop.  I did not reboot it, however because it was idle for a long time between requests I believe it was suspended and then restarted from the server end.  Is there something specific that you want me to try?

**Comment by jreichert** [comment]
The issue is mostly resolved now.  I contacted Shadow support and they said they "made some changes" to my VM (no idea what exactly because they didn't say).  After that, my mouse & keyboard were detected without any changes from my side.  Right click still does not work and scroll speeds are too jumpy, but otherwise it is now working as expected.
