### ISSUE TITLE
Unusable on Linux Mint 19 with Intel processor/graphics

### ISSUE THREAD

**Issue by michael-karpinski** [NicolasGuilloux/blade-shadow-beta#22]
I am able to launch Shadow on my Linux laptop, but the application is unusable after launching. The bottom third of the screen is teared/blurry and mouse input is not working.

**System**
 - OS: Linux Mint
 - OS Version: 19
 - Environment: Cinnamon 3.8.9
 - Application: AppImage
 - Application Version: 0.8.62

**Configuration**
 - The user is in input group ? Yes
 - The environment uses Xorg ? Can not check - Driver Manager says "No proprietary drivers in use" and has no drivers displayed.
 - VA API detects H264 ? And H265 ? H264, yes.

Debug log: https://gist.github.com/karpimpski/9a3e14c557850d91e0fdfec7b781acf3

**Comment by NicolasGuilloux** [comment]
Hi! Thanks for reporting the bug. An issue is already open about this : #12
This should be fixed in the next update according to the dev, but there is no date yet. We just have to wait for it ;)
