### ISSUE TITLE
No Keyboard or Mouseinput

### ISSUE THREAD

**Issue by holger-dev** [NicolasGuilloux/blade-shadow-beta#23]
Hi,
i have absolutly no mouse/keyboard input into the shadow! In Windowmode there is a mouse, in fullscreen the mouse is there, but invisible and no keyboard-interaction.

System

OS: Ubuntu
OS Version: 18.04
Environment: XORG/GNOME
Application: AppImage
Application Version: 2.0.4
Configuration

The user is in input group ? YES
The environment uses Xorg ? YES
VA API detects H264 ? And H265 ? H264, NO H265 (disabled)
To Reproduce Steps to reproduce the behavior:

**Comment by NicolasGuilloux** [comment]
Hi mate!
The last update is sadly broken. The cursor is hidden in full-screen mode and there is no keyboard capture.
I recommand to stay on the previous build, available at https://nicolasguilloux.github.io/blade-shadow-beta/

Cheers for the issue, we will keep the community in touch if somebody finds a workaround!

**Comment by Eliaenor** [comment]
Hi there !

To add information about it, I have keybord input but it only capture a character every 5-10 seconds (Time is very random but feels like a medium of 5 seconds) while holding a key down.

Hopes it help you guys !

**Comment by peshane** [comment]
Got exactly the same behavior on my side

**Comment by LindezaGrey** [comment]
hey, i don't know how related this topic is but i installed the latest "official" version 0.9.24, which seems to work normally except shortcuts are not working (e.g. for fullscreen)
what's the best way to give feedback to the shadow developers?

**Comment by NicolasGuilloux** [comment]
Hi!
So you have a cursor in full-screen mode and keyboard inputs?

The shortcut changed (again). Try Special key + Alt + f to toggle the full-screen

**Comment by LindezaGrey** [comment]
OMG! I feel dumb :'D thats it. yeah the official release is working fine then... I am on Ubuntu 18.10 by the way. Thanks for the tip!
