### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by louis030195** [NicolasGuilloux/blade-shadow-beta#25]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25003283/54486009-8670d280-4882-11e9-85f8-dbfbbb5d0cb2.png)
It restart Shadow and do this again (when trying to start the stream)

**System**
 - OS: Ubuntu
 - OS Version: 18.04
 - Environment: Gnome
 - Application: AppImage
 - Application Version: 2.0.0.7

**Configuration**
 - The user is in input group ? Yes
 - The environment uses Xorg ? ?
 - VA API detects H264 ? And H265 ? Yes

**To Reproduce**
1. Start Shadow
2. Log in
3. Click start

PS:

It was working fine before it asks me to update

**Comment by louis030195** [comment]
Workaround: reinstall Shadow manually

**Comment by NicolasGuilloux** [comment]
Hi mate :)
The new launcher came out and the old one is deprecated now. As the new release gives a lot of improvement, I recommand people to download the application from the website again.

Thanks for the feedback :)
