### ISSUE TITLE
PKGBUILD errors when building from source

### ISSUE THREAD

**Issue by samsonvd** [NicolasGuilloux/blade-shadow-beta#27]
**Describe the bug**
Running the install script from a freshly cloned repo causes a 404 error.

**System**
 - OS: Arch
 - OS Version: n/a
 - Environment: Xorg + AwesomeWM
 - Application: source
 - Application Version: Commit 62a4e7b5

**Configuration**
 - The user is in input group: Y
 - The environment uses Xorg: Y
 - VA API detects H264: Y
   - And H265: Y

**To Reproduce**
1. Clone `https://github.com/NicolasGuilloux/blade-shadow-beta`
2. `cd blade-shadow-beta/Arch`
3. `chmod +x install_arch.sh`
4. `./install_arch.sh`

**Screenshots**

```
❯ makepkg -f
==> Making package: shadow-beta 0.8.62-2 (Wed 20 Mar 2019 14:59:41 GMT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading shadow-alpha-bionic.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading https://macosx.update.blade-group.fr/mpl/linux/beta/bionic/shadow-alpha-bionic.zip
    Aborting...
```

**Additional context**

**Comment by NicolasGuilloux** [comment]
Hello!
As you can see now, the script is no longer available on this Github.
If you want to build it from the terminal, please get the version from the AUR package.

The script was made before the AUR  package but keeping it on this repo wasn't make sense.

Sorry for the inconvenience!
