### ISSUE TITLE
Feature Request: Add undetected gamepad to issues

### ISSUE THREAD

**Issue by avallete** [NicolasGuilloux/blade-shadow-beta#3]
Add the undetected gamepad to the list of the 'Well known issues'.

**Comment by NicolasGuilloux** [comment]
Hello,
this issue is already explained over there: https://nicolasguilloux.github.io/blade-shadow-beta/issues.html

Do you want me to add something ? :)

**Comment by avallete** [comment]
I'm only seeing the trackpad problem on this issue.

It's unclear if it also concern gamepad.

Also, from some intels I've get on the Discord, the gamepad problem can be 'dirty fixed' using Hamachi+Virtual Here

**Comment by NicolasGuilloux** [comment]
Oh sorry, I read trackpad. I'll do it soon ;)

**Comment by avallete** [comment]
Already made a PR about this topic, feel free to look on it ;)

https://github.com/NicolasGuilloux/blade-shadow-beta/pull/4
