### ISSUE TITLE
Mouse and fullscreen grabbing not working

### ISSUE THREAD

**Issue by samsonvd** [NicolasGuilloux/blade-shadow-beta#30]
**Describe the bug**

The shortcuts to toggle fullscreen and input grab do not do anything.

**System**
 - OS: Arch
 - OS Version: n/a (latest) 
 - Environment: Xorg + AwesomeWM
 - Application: source
 - Application Version: Commit 62a4e7b

**Configuration**
 - The user is in input group
 - The environment uses Xorg
 - VA API detects H264 and H265.

**To Reproduce**
1. Start Shadow and the stream
2. Put the mouse in the window.
3. Press Ctrl+Shift+f or Ctrl+Shift+g
4. Nothing happens

**Screenshots**
n/a

**Additional context**

Mouse is still grabbed by Shadow (you can interact with the instance), but if you move the mouse too far in any direction it leaves the window. 

When you start Shadow in fullscreen, everything works well, but there is now way to exit. Shortcuts for moving to other desktops don't work, all keyboard input is forwarded to Shadow.

**Comment by aarnoud** [comment]
please try to install libsndio6.1-compat and try again

**Comment by subjectdenied** [comment]
with archlinux this package is in the aur and is called "libsndio-61-compat", and this doesnt bring me the cursor back in fullscreen btw

**Comment by aarnoud** [comment]
side note, shortcut has changed since version 4.1.x
- Super Key + Alt + F     Fullscreen toggle
- Super Key + Alt + M   Input toggle
- Super Key + Alt + Q    Close the stream

**Comment by aarnoud** [comment]
and a workaround has been submitted by community:

- 'Mouse trail' inside the cursor options of Windows
- Set trail to short

until a better option or a fix.

**Comment by Abde5** [comment]
Workaround not working when playing full screen games (overriding windows cursor parameters)...
