### ISSUE TITLE
Arch version fails to build (includes proposed fix)

### ISSUE THREAD

**Issue by dylanmtaylor** [NicolasGuilloux/blade-shadow-beta#31]
As of the new version, I'm having issues installing this on Arch linux via the AUR. I did some digging and discovered that the md5sum changed and the location and name of the .desktop file have also been modified. I was able to get it to build with a few modifications:

The md5sum of the file actually downloaded was d47e22482755a2fc73061860c09d41ac - this might need updated in the source code. If you put this value into PKGBUILD after cloning the repo and run makepkg, it works:

```
source=('https://shadow.tech/linux/shadow-beta.zip')
md5sums=('d47e22482755a2fc73061860c09d41ac')
```

The .desktop file, it is actually named shadow-dev.desktop in the new archive so the PKGBUILD script should be updated to reflect this:

```
	### Edit launcher
	sed -e 's/^Categories=.*$/Categories=Games;Game;Utility;Virtualization/g' "${pkgdir}/usr/share/applications/shadow-dev.desktop" > shadow-beta.desktop
	chmod g-w shadow-beta.desktop

	rm "${pkgdir}/usr/share/applications/shadow-dev.desktop"
	mv shadow-beta.desktop "${pkgdir}/usr/share/applications/shadow-beta.desktop"
```

Please update this so that others can benefit :)

**Comment by NicolasGuilloux** [comment]
AUR package updated, thanks to you :)
