### ISSUE TITLE
App does not start up: JavaScript error

### ISSUE THREAD

**Issue by nitardus** [NicolasGuilloux/blade-shadow-beta#34]
**Describe the bug**
After the installation of the app (as described in README.md) the program does not start up. When started from console, I get this error message:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.5vD1nP: Fehler beim Mappen des Shared Objects
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/Shadow Beta/resources/app.asar/release/main/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/opt/Shadow Beta/resources/app.asar/release/main/node_modules/keytar/lib/keytar.js:61:3)

The same occurs with the App.Image. The app from https://shadow.tech/dede/applications starts up and connects to the machine, but takes minutes to do so and is not usable due to unresponsiveness. It can't be the fault of my internet connection, which is very fast, and I am connected by cable.

**System**
 - OS: Linux Mint
 - OS Version: 19.1
 - Environment: Cinnamon
 - Application Version: 4.3.1

**Configuration**
 - The user is in input group
 - The environment uses Xorg
 - VA API detects H264, not H265
 - diagnostic tool says all libraries installed
 - this is the output of vainfo:

vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Ivybridge Mobile - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD

Here I have uploaded the report:
https://nicolasguilloux.eu/hostbin/3478874270

**Comment by aarnoud** [comment]
hey @mayhoth try to install a keychain, like gnome-keychain ?

Regarding connection time can you post screenshot of http://speedtest.ams.shadow.guru ?

**Comment by nitardus** [comment]
Here you go...

![grafik](https://user-images.githubusercontent.com/50620861/57725242-f89c4280-768c-11e9-8401-0d8d9b3b97f0.png)


I did not find anything about a gnome-keychain. Did you mean gnome-keyring? That is already the newest version on my system...

**Comment by aarnoud** [comment]
if not fixed already, download latest beta appimage from your account / Applications, delete any shadow/blade folders in : ~/.cache/ & ~/.config/ and try again.
