### ISSUE TITLE
Can't start streaming on Fedora 30

### ISSUE THREAD

**Issue by chadrien** [NicolasGuilloux/blade-shadow-beta#35]
**Describe the bug**
App starts but clicking "Start now" doesn't. It says "something unexpected happened", with error code `R:0x7F`

**System**
 - OS: Fedora
 - OS Version: 30
 - Environment: i3
 - Application: AppImage
 - Application Version: Launcher 4.4.19 | Client 2.5.0

**Configuration**
 - The user is in input group ? Yes
 - The environment uses Xorg ? Yes
 - VA API detects H264 ? And H265 ? Yes

**To Reproduce**
1. Go to the launcher
2. Click on 'Start now'
3. See error

**Comment by ghost** [comment]
I have the same error on Fedora 30. "R:0x7F".

**Comment by ghost** [comment]
Okay I found a solution and fixed it. 

I installed a few missing dependencies and `mesa-libGLES` fixed it. @chadrien

**Comment by chadrien** [comment]
@davidjendreizak Thanks for the pointer! Can you list the other packages you installed? I tried installing `mesa-libGLES` and still have the same error. All I have is `libva`, `libva-intel-driver` (as per README instructions) and `mesa-libGLES` (from your suggestion). So I'm guessing another dep you installed is required.

**Comment by ghost** [comment]
I installed `mesa-libGLES, openssl-devel, ubsan(libubsan), libbsd, nss-tools, libappindicator, gconf-editor(maybe not needed)`.

**Comment by chadrien** [comment]
Thanks a lot! I'll try to install only the minimum out of it until it works so that we can have a list of what's required.

**Comment by chadrien** [comment]
Alright, for me `libbsd` was the only one required, on top of `libva` and `libva-intel-driver`. I could even remove `mesa-libGLES` and still get it working.

Edit: I got it to work *once* in i3. Now it kinda freezes the screen (the mouse still reacts as it's supposed to, I can click things where they should be and it will work). On gnome it works perfectly.

**Comment by ghost** [comment]
So it solved your problem and libbsd is the missing dep? @chadrien

**Comment by chadrien** [comment]
Yes, `libbsd` was the only thing missing for me. Still an issue in i3 as stated in the edit of my previous comment, but probably i3 related.

**Comment by Adrien2002** [comment]
I'm having the same issue : R:0x7f
I wanted to give a try with Xubuntu 19.10 and I have libbsd installed, I tried all packages listed above, none of them made Shadow work on Xubuntu. It works well on Arch Linux with the same hardware. vainfo tells me I do have both x264 and x265. I'm running on an Intel UHD Graphics 600 and "va" for Intel is installed. Yet, I still have this issue. What could be missing this time ?

**Comment by ghost** [comment]
Hi @Adrien2002. I hope your problem is solved by now. If not, you may try this: 
`sudo apt install gconf2 libgles2-mesa libubsan0 libuv1 libva-glx2`.
Everytime you download the Shadow app look for dependencies in the .deb file: `dpkg -I Shadow.deb`
You will see a list of dependencies.
