### ISSUE TITLE
No Graphical updates on Fedora30

### ISSUE THREAD

**Issue by joker-119** [NicolasGuilloux/blade-shadow-beta#36]
**Describe the bug**
The mouse cursor moves around in both non-captured and captured-mouse mode, however nothing else on the screen moves/updates graphically. The Shadow **is** running and working normally during this (confirmed through parsec).

**System**
 - OS: Fedora
 - OS Version: 30
 - Environment: MATE
 - Application: Appimage/OfficialAppimage/Official AppImage.beta
 - Application Version: 4.4.24(client 2.8.2)/4.5.3(client2.11.5)

**Configuration**
 - The user is in input group ? Yes
 - The environment uses Xorg ? Yes
 - VA API detects H264 ? And H265 ?Unsure how to check, vainfo doesn't mention anything about either at all

**To Reproduce**
1. Open app
2. Click start stream
3. Die inside

**Screenshots**

**Additional context**
va output:
```[Joker@Amathorian ~]$ vainfo
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.4 (libva 2.4.0)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API - 0.7.4
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG4Simple            :	VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    :	VAEntrypointVLD
      <unknown profile>               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD```

NVidia Driver Version: 430.26 - GTX 1660Ti, AMD FX-8350 CPU.

**Comment by aarnoud** [comment]
should be fixed, if not check https://github.com/NicolasGuilloux/blade-shadow-beta/issues/35

**Comment by feragon** [comment]
I encountered the same problem with a NVS 4200M and nvidia drivers 390.87. 
Replacing the proprietary driver with nouveau (with [nvidia firmware](https://nouveau.freedesktop.org/wiki/VideoAcceleration/)) solved it.
