### ISSUE TITLE
the launcher failed to connect to Shadow

### ISSUE THREAD

**Issue by pr0grammr** [NicolasGuilloux/blade-shadow-beta#37]
when im trying to run shadow and click on "Start now", i get the error "the launcher failed to connect to shadow (code: L:100)" .. 

i am using Ubuntu 19.04 with KDE Plasma 5 and Nvidia MX 150 graphic card.

i googled a lot but didnt find anything matching this issue. 
any ideas? :/

**Comment by NicolasGuilloux** [comment]
Hello mate !
We will need more information about your setup. Can you print here the `vainfo` result please ? (`sudo apt install vainfo`)

**Comment by pr0grammr** [comment]
output is: 

```bash
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

**Comment by pr0grammr** [comment]
any ideas? :thinking:

**Comment by NicolasGuilloux** [comment]
NVIDIA MX 150 cards may not be supported by the VA-API. You will have to tweak to have a nice `vainfo`.

A tutorial is available over [here](https://nicolasguilloux.github.io/blade-shadow-beta/#vainfo). If you succeed to make it work, please give your feedback over here :) You may find some help from the Discord community aswell.

**Comment by NicolasGuilloux** [comment]
Did you succeed to run it?

**Comment by NicolasGuilloux** [comment]
I close this very old issue. You can reopen it if you want.

**Comment by pr0grammr** [comment]
no, i didnt succeed but doesn't matter now. :)
