### ISSUE TITLE
Doesn't recognize keyboard and mouse on Ubuntu 18.04

### ISSUE THREAD

**Issue by Mildred34** [NicolasGuilloux/blade-shadow-beta#42]
Hi,

I've been trying Shadow on Ubuntu 18.04. 
I could connect through the AppImage, but afterwards when i get to the windows screen, I can't use my keyboard nor my mouse.

If you have any idea why, it would help me a lot.

BR,

Alexis

**Comment by aarnoud** [comment]
you still have the issue ?
