### ISSUE TITLE
Recurrent black screen issue on both Beta and Alpha

### ISSUE THREAD

**Issue by Asphahyre** [NicolasGuilloux/blade-shadow-beta#43]
**Describe the bug**
When the stream is starting, the cursor appears (drawn from the host) but the screen is entirely black.

**System**
 - OS: Gentoo
 - OS Version: Linux 5.0.5-gentoo #2 SMP Fri Apr 5 16:14:13 CEST 2019 x86_64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GenuineIntel GNU/Linux
 - Environment: Gnome on Xorg
 - Application: AppImage
 - Application Version, **Stable** (working): 4.8.14 | Client: 2.15.7
 - Application Version, **Beta** (worked twice, but not atm): 4.10.13 | Client: 2.15.7
 - Application Version, **Alpha** (never worked): 4.10.13 | Client: 2.16.3
 - Graphic card in use: `VGA compatible controller: Intel Corporation Device 591b (rev 04)`

**Configuration**
 - [x] The user is in input group?
 - [x] The environment uses Xorg?
 - [x] VA API detects H264? And H265?

**To Reproduce**
Steps to reproduce the behavior with Beta
1. Open the Beta launcher
2. Update the VM
![image](https://user-images.githubusercontent.com/8136122/68077379-286a0e80-fdc3-11e9-800a-833f0a311535.png)

3. Start the stream
4. The stream may work (or not)
5. Update the Shadow on the VM side, “There is a Shadow update”, from within the stream
6. When the Shadow will be up again, the stream will restart and be black
7. Restart the whole launcher, and the stream will restart black again
—————
1. Open the Alpha launcher
2. Update the VM
3. Start the stream
4. The stream will be always black

**Screenshots**
![image](https://user-images.githubusercontent.com/8136122/68077362-b691c500-fdc2-11e9-81a4-d8eb8a6d8910.png)

You can see in yellow, at the top, the network usage at 5Mbps while the stream is started.

**Additional context**
That's tested with and without the low bandwidth mode.

Everything (like shortcuts) seems to be ok except the black screen.

[Here are the error logs in Alpha](https://pastebin.com/raw/zn4Yj87m), I'm not able to retrieve the same errors on Beta nor prod.

```
# vainfo
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.4 (libva 2.4.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Kaby Lake - 2.4.0.pre1 (2.3.0-11-g881e67a)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSlice
      VAProfileVP9Profile2            : VAEntrypointVLD
```

**Comment by NicolasGuilloux** [comment]
@Asphahyre As the application evolves quite quickly, do you mind checking if this bug is still happening please ?

**Comment by Astanusic** [comment]
I have the same issue, with i965 drivers it work like a charm. Once i update my nvidia drivers the stream start but stay black. Or i can see the first image and then it freeze.

**Comment by aarnoud** [comment]
> I have the same issue, with i965 drivers it work like a charm. Once i update my nvidia drivers the stream start but stay black. Or i can see the first image and then it freeze.

Nvidia GPU is not supported by shadow or through this hack but not in a stable state : https://gitlab.com/aar642/libva-vdpau-driver
