### ISSUE TITLE
Fedora 31 -> black screen with beta launcher/ fixed image screen with normal launcher

### ISSUE THREAD

**Issue by changemenemo** [NicolasGuilloux/blade-shadow-beta#45]
**Describe the bug**
black screen when the renderer is connected with beta launcher
fixed image screen when the renderer is connected with the normal launcher

**System**
 - OS: Fedora
 - OS Version: 31
 - Environment: Gnome
 - Application: AppImage
 - Application Version: 4.10.41 for beta 4.10.30 for normal
 
**Configuration**
 - The user is in input group ? yes
 - The environment uses Xorg ? yes
 - VA API detects H264 ? And H265 ? H264
```
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.6 (libva 2.6.0.pre1)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API - 0.7.4
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG4Simple            :	VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    :	VAEntrypointVLD
      <unknown profile>               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
```
For future references, the libva-vdpau-driver needed to be installed separately from the vainfo package.

is this GPU too old to handle it?
the linux steam API to render compatible games not compatible with linux seems to work fine. On the other hand the number of lines from VA-API seems a little poor.

**Comment by changemenemo** [comment]
```
./Shadowofficiel/Shadow.AppImage 
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en): No such file or directory
Checking for update
Update for version 5.0.289 is not available (latest version: 5.0.289, downgrade is disallowed).

```

That's the official shadow image app. And I have a fixed image. The keyboard or mouse stream seems to go through since I think I can login to it, but the image doesn't change. It's stays a fixed image at all time...
No clue why is this happening?

**Comment by aarnoud** [comment]
try with this: https://gitlab.com/aar642/libva-vdpau-driver

**Comment by NicolasGuilloux** [comment]
@boistordu Is it working with the Arekinath's patch ?

**Comment by changemenemo** [comment]
I can't try it anymore since I don't have a shadow anymore because of a problem with their payment system, they are still investigating for a month now. I have to wait for my pre-ordered new shadow configuration to arrive first then I will be able to test it again.

**Comment by NicolasGuilloux** [comment]
Okay, sorry to ear that :(

I close this issues but feel free to open it again when you have your Shadow. Moreover we are on the Discord so contact us if you need help (with a ping :))

**Comment by changemenemo** [comment]
So I got a temporary shadow back until my pre-order is ready.
the AppImage is up to date and I just started the shadow so I'm at the installation but that shouldn't matter I guess.

still fedora 31, up to date. with a 1080Ti 
so I have:
$ vainfo
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.6 (libva 2.6.0.pre1)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API - 0.7.4
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG4Simple            :	VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    :	VAEntrypointVLD
      <unknown profile>               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD

still a black screen

**Comment by changemenemo** [comment]
so is the patch still needed? 
if yes, I'm sorry but you will have to walk me through the process because ! don't necessarely get the context. I already have problems to install cuda, probably because I don't see how it fits into the OS architecture so this driver in particular I won't see it either. 
So is it a kernel patch? Which means that I should recompile my kernel with it? Or is it just a modprobe thing to activate?
