### ISSUE TITLE
Erreur L-100 à répétition

### ISSUE THREAD

**Issue by skyline-ch** [NicolasGuilloux/blade-shadow-beta#48]
**Describe the bug**
Comme demander par Nover#9563 sur discord, j'ouvre donc se report.
cela fais maintenant quelques mois que je contact régulièrement le support qui n'en nas pas vraiment a faire des personne sur Linux, la seul choses que l'on me dis c'est qu'il sont intervenu sur mon Shadow et que le problème devrais être régler, donc j'abandonne de les contacter.

J'utilise shadow principalement sur mon PC Fix (voir journal lien détailler si dessous), la version beta ne fonctionne pas depuis de nombreux mois voir meme 1ans il me sembe a cause d'un moteur de compression du flux ou je me souviens plus quoi, justement des L-100 à répétition, la version stable a fonctionner jusqu’à se qu'il y ai une mise à jours (il me semble que cela correspond a l'ajout de l'annonce de la nouvelle fonction win+alt+O.

Depuis sur la version stable qui fonctionnais très bien je n’arrive plus ou dans de rare cas a me connecter.

Se qu'il se passe, je lance l'app, j'arrive sur la page pour lancer le strem, je clique sur "c'est parti", la une fraction de seconde la fenêtre du strem s'ouvre et se ferme je me retrouve sur la page de lancement de shadow avec le message en bandeau en bas, erreur L-100.
Je peux insister durant 1h et ne pas arriver a me connecter, par fois par miracle cela ne plante pas.
et je peux donc utiliser shadow sans problème et confortablement a part quelle artefact sonore par moment.
J'en déduit donc que mon PC pour la version stable est capable de faire tourner shadow, mais qu'il y as un problème qui le fais planter au lancement dans la plus part des cas

La version Beta na plus fonctionner depuis très longtemps, je teste de temps en temps sans succès

Résultat de  : 
`curl https://raw.githubusercontent.com/NicolasGuilloux/blade-shadow-beta/master/scripts/report.pl | perl`

Config et log : https://nicolasguilloux.eu/hostbin/4166355277

**Comment by skyline-ch** [comment]
A ton des nouvelles ?

L'autre jour j'ai pus me connecter après 2 L-100, aujourd'hui et hier soir impossible après avoir tenter depuis plus de 30mn à cliquer su se fichu bouton

**Comment by NicolasGuilloux** [comment]
Summary :

Ubuntu 18.04
GPU Nvidia GT 640 (H264 only)
No missing libraries. On Xorg. 

Crash happens since the Quick Menu implementation apparently. Sometimes it works though.

**Comment by skyline-ch** [comment]
Tester avec la Beta.
J'ai pus voir durant 1 seconde le bureau à plusieurs fois mais la fenêtre se ferme à chaque fois
https://nicolasguilloux.eu/hostbin/101269281

**Comment by skyline-ch** [comment]
Je viens de tester avec une version installer qui est restée d'y as un moment (par une appImage, mais un package) en version BETA 4.2.1 client 2.0.5, ça fonctionne pour le flux vidéo, pas de L-100 ....
Par contre pas de contrôle de souris, ni de son

Si je lance depuis le mobile un vidéo YouTube sur Shadow et que je lance en suite la version sur le PC qui me fais des L-100, une fraction de seconde j'ai le son du shadow

si ça peux aider a comparer les versions pour trouver une piste a explorer

**Comment by skyline-ch** [comment]
Voici les logs de la tentative qui as fonctionner avec la version stable après de très nombreuses tentatives

https://nicolasguilloux.eu/hostbin/4015124843

**Comment by skyline-ch** [comment]
Tours rien a demander ou proposer pour résoudre le soucis ?

**Comment by skyline-ch** [comment]
Toujours Rien, personne pour s'occupé de cela ?

**Comment by skyline-ch** [comment]
ça fais 2-3 jours que j'ai le stream qui croche et lache au bout de 2-5 seconde, pas a tout les coup mais parfois, le reste du temps je voie pas le bureau ça plante avant

Ca dois se trouver dans les dernière ligne du logs:
https://nicolasguilloux.eu/hostbin/2845573220

A part ça les monologue je suis pas fans

**Comment by NicolasGuilloux** [comment]
Bonjour,

Désolé, j'ai une vie et j'ai pas trouvé le temps en 1 mois de répondre correctement à cette issue.
On a assigné MomoK dessus mais les problèmes sur l'application Linux sont très longs à résoudre car l'application Linux n'est pas la priorité.

Le but d'avoir fait cette issue sur Github est de fournir une base sur laquelle les développeurs peuvent travailler mais ça ne veut pas dire qu'ils vont répondre. Je pense qu'il y a suffisament de données pour qu'ils se débrouillent pour le moment.

Pour rappel, en dehors des devs, on est tous bénévoles et ne sommes pas affilié à Blade. On fait de notre mieux pour aider ;) Merci d'avoir rapporté l'issue. Je te laisse revenir sur le Discord pour pouvoir avoir moins de monologue.

**Comment by skyline-ch** [comment]
> _This comment has been moderated. Checkout our [Code of Conduct](https://github.com/NicolasGuilloux/blade-shadow-beta/blob/master/CODE_OF_CONDUCT.md)._

**Comment by NicolasGuilloux** [comment]
Ce Github n'est PAS officiel, c'est un Github fait par des utilisateurs lambda qui veulent aider, et on a ajouté un dev pour pouvoir trier et remonter des issues avec autant d'efficacité que possible, même si ce n'est pas forcément très efficace pour autant.

Il n'y a aussi aucun support sur ce Github ni aucune garantie. Étant non officiel, aucun membre du staff n'est tenu de passer ici pour faire du support. Ce Github est un support pour centraliser certaines informations relatifs au Bug et ainsi facilement les communiquer aux devs lors d'un dialogue avec eux. 

Je comprends ta frustration, et j'acquiesse même sur certains points. Toutefois je n'approuve pas le langage. De plus, ce Github n'est pas là non plus pour les plaintes. Ce n'est simplement pas le lieu pour les formuler. 

Je te laisse donc aller sur le Discord officiel de Shadow pour les faire remonter et ainsi avoir une réponse tout aussi officielle. Tu pourras même en discuter avec la communauté d'utilisateurs dont j'en fais partie, et des représentants officiels de Shadow.

Bonne journée !   

PS : tu mets toutefois en lumière que nous avons mal prévenu les utilisateurs que ce Github n'est pas officiel. Je vais remanier dès ce soir le ReadMe pour mieux mettre en valeur la non affiliation de ce dépôt avec Blade.

**Comment by aarnoud** [comment]
see issue linked
