### ISSUE TITLE
Cannot stream on Fedora 31

### ISSUE THREAD

**Issue by fbouynot** [NicolasGuilloux/blade-shadow-beta#49]
**Describe the bug**
App starts but clicking "Start now" doesn't. It says "something unexpected happened", with error code R:0x7F

**System**
 - OS: Fedora
 - OS Version: 31
 - Environment: Gnome
 - Application: Appimage
 - Application Version: ALPHA - Launcher 4.12.2 - Client 2.17.21

**Configuration**
 - The user is in input group ? YES
 - The environment uses Xorg ? YES
 - VA API detects H264 ? And H265 ? YES / NO

**To Reproduce**
1. Go to the launcher
2. Click on 'Start now'
3. See error

**Additional context**
Similiar to this bug : https://github.com/NicolasGuilloux/blade-shadow-beta/issues/35
Although, I did `dpkg -I ShadowAlpha.deb` and manually found matching package for Fedora 31, and installed them if they wasn't already. I got the ShadowAlpha.deb from last post [Here](https://github.com/NicolasGuilloux/blade-shadow-beta/issues/12)

    dpkg -I ShadowAlpha.deb | grep Depends
    Depends: gconf2, gconf-service, libnotify4, libappindicator1, libxtst6, libnss3, libcurl3-gnutls, libva-glx2, libva-x11-2, libva2, libdrm2, libfreetype6, libbsd0, libjson-c3, libopus0, libubsan0, libuv1, libsndio6.1, libssl1.1, libgles2-mesa

The Beta version do the same, and the prod one is "working", I can launch the Stream but everything 
is freezing and sometimes half of the screen is green (I'll open another issue - edit: [here](https://github.com/NicolasGuilloux/blade-shadow-beta/issues/50)), I did install Beta / Alpha in the expectation of having the Intel HD4000 fix.

Do you know if some new dependency has been added since the similar bug?

[vainfo.txt](https://github.com/NicolasGuilloux/blade-shadow-beta/files/4205591/vainfo.txt)

**Comment by aarnoud** [comment]
the dependency list of .deb is incomplete, 0x7F most of the time is lack of libva-glx2, but to make sure, start Shadow.AppImage then `find /tmp -name Shadow -exec ldd {} +` and post result here.,

**Comment by fbouynot** [comment]
Thank you, it looks like libcef and libsentry_crashpad are missing but not available.

    $ find /tmp -name Shadow -exec ldd {} +
	linux-vdso.so.1 (0x00007ffe109e3000)
	libSDL2-2.0.so.0 => /lib64/libSDL2-2.0.so.0 (0x00007f1bca72e000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f1bca5e8000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f1bca5db000)
	libcef.so => not found
	libsentry_crashpad.so => not found
	librt.so.1 => /lib64/librt.so.1 (0x00007f1bca5d0000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1bca5ac000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f1bca5a5000)
	libva.so.2 => /lib64/libva.so.2 (0x00007f1bca57e000)
	libGLESv2.so.2 => /lib64/libGLESv2.so.2 (0x00007f1bca568000)
	libva-glx.so.2 => /lib64/libva-glx.so.2 (0x00007f1bca560000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f1bca366000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f1bca21e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1bca204000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1bca03b000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f1bca010000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f1bc9ffb000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f1bc9fee000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1bcb260000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f1bc9f2f000)
	libva-x11.so.2 => /lib64/libva-x11.so.2 (0x00007f1bc9f27000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f1bc9f1e000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f1bc9f0a000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f1bc9e76000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f1bc9e70000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f1bc9e3a000)

    $ sudo dnf whatprovides libcef.so
    Dernière vérification de l’expiration des métadonnées effectuée il y a 0:15:44 le lun. 17 févr. 2020 14:31:28 GMT.
    Erreur : Aucune correspondance trouvée

    $ sudo dnf whatprovides libsentry_crashpad.so
    Dernière vérification de l’expiration des métadonnées effectuée il y a 0:15:58 le lun. 17 févr. 2020 14:31:28 GMT.
    Erreur : Aucune correspondance trouvée

**Comment by MichaelTrip** [comment]
I have the same issue. Tested both the beta and the stable client. I get a (Error code: R-0x7F). It was working until today. 

Here is my ld output:
```
	linux-vdso.so.1 (0x00007ffe15ae3000)
	libSDL2-2.0.so.0 => /lib64/libSDL2-2.0.so.0 (0x00007f148eae0000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f148e998000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f148e988000)
	libsentry_crashpad.so => not found
	librt.so.1 => /lib64/librt.so.1 (0x00007f148e978000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f148e950000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f148e948000)
	libva-x11.so.2 => /lib64/libva-x11.so.2 (0x00007f148e940000)
	libva.so.2 => /lib64/libva.so.2 (0x00007f148e918000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f148e718000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f148e5d0000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f148e5b0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f148e3e0000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f148e3b0000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f148e398000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f148e388000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f148f550000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f148e378000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f148e360000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f148e358000)
```

**Comment by aarnoud** [comment]
have a try at Shadowcker, until someone got some time to test on Fedora : https://gitlab.com/aar642/shadowcker

**Comment by fbouynot** [comment]
Thank you aarnoud,

FYI shadowcker is working, I switched on it since it was advised to me in https://github.com/NicolasGuilloux/blade-shadow-beta/issues/50

@MichaelTrip I think we don't have the exact same issue, since for me the stable version did launch (but I had performance issue)
Can you try to install these and see if you still have the issue on stable?

    dnf install -y GConf2 libnotify libappindicator libXtst nss libcurl gnutls libva libdrm freetype libbsd json-c opus libubsan libuv mesa-libGLES compat-openssl10 libsndfile

**Comment by MichaelTrip** [comment]
@aarnoud: The Shadowcker works great. Thanks! Should i create a new issue for my problem?
@fbouynot: Just added those packages, but unfortunately it didn't work. :(

**Comment by aarnoud** [comment]
@fbouynot can you elaborate on performance issue it's on all versions you have them or all ? what's your cpu & gpu exact model ? you tried using alpha `make alpha` on shadowcker ?

@MichaelTrip can you post please your shadow.log located in `~/.cache/blade/shadow/` ?

**Comment by MichaelTrip** [comment]
@aarnoud I will try post it tonight, maybe tomorrow!

**Comment by fbouynot** [comment]
@aarnoud I have no performance issue on shadowcker, only with the Appimage.
On the Appimage, I can only launch the stable version (alpha and beta gives 0x7f), and this stable version makes every single application, including Shadow, freezing and actualizing randomly every 10s-1mn.

I only tried the beta shadowcker, it does work great.

**Comment by charlie-haley** [comment]
I'm getting same issue on Arch Linux. Was working fine a few days ago and has randomly stopped working.

**Comment by MichaelTrip** [comment]
@aarnoud these are the log file i could gather.
[shadow-launcher.log](https://github.com/NicolasGuilloux/blade-shadow-beta/files/4240174/shadow-launcher.log)
[shadow-launcher-2020-02-22-00.log](https://github.com/NicolasGuilloux/blade-shadow-beta/files/4240176/shadow-launcher-2020-02-22-00.log)

**Comment by aarnoud** [comment]
@MichaelTrip no `shadow.log` indicates missing dependencies, I'll try to install Fedora 31 this week and check

**Comment by MichaelTrip** [comment]
> @MichaelTrip no `shadow.log` indicates missing dependencies, I'll try to install Fedora 31 this week and check

Thanks for your work on this :) The docker version runs fine btw, using it every evening :)

**Comment by aarnoud** [comment]
@MichaelTrip ok just installed Fedora 31 in a VM,

 minimum requirements **for intel iGPU ** with Shadow.AppImage (stable) are :

`sudo dnf install libva libcurl libva-utils`

**for intel GMA** :

`sudo dnf install libva libva-intel-hyrbrid-driver libcurl libva-utils`

**for NVIDIA** :

`sudo dnf install libva libva-vdpau-driver libcurl libva-utils` + installation of patched driver https://gitlab.com/aar642/libva-vdpau-driver

with this you should get have at least a shadow.log in `~/.cache/blade/shadow/`

**Comment by aarnoud** [comment]
for the missing libs they are provided by appimage, even if, at least on fedora full dependency are not available or install-able using dnf... (ex: librtmp on provided libcurl), but they should not lock shadow or be an issue.

**Comment by MichaelTrip** [comment]
> for the missing libs they are provided by appimage, even if, at least on fedora full dependency are not available or install-able using dnf... (ex: librtmp on provided libcurl), but they should not lock shadow or be an issue.

Hi aarnoud,

You nailed it! I was missing librtmp. I have installed it, and now it works ! Thanks again!

**Comment by Hedius** [comment]
librtmp is available on rpm fusion: ;)
https://fedora.pkgs.org/31/rpmfusion-free-x86_64/librtmp-2.4-15.20190330.gitc5f04a5.fc31.x86_64.rpm.html

I can confirm that this fixes the problems. THX :)

**Comment by NicolasGuilloux** [comment]
I updated the ReadMe and the website :) Thanks guys for the reports and for the solution.
I close this issue, you will spend your free time gaming, not reporting issue now :p
