### ISSUE TITLE
Stream freezing all applications and graphical bug on lower screen space

### ISSUE THREAD

**Issue by fbouynot** [NicolasGuilloux/blade-shadow-beta#50]
**Describe the bug**
App starts but streaming is freezing all applications (including Streaming) but mouse movement (mouse click is impacted). The bottom half is sometimes not refreshing, sometimes green (maybe sometimes ok, hard to say because it is so slow I cannot really try to display things)

**System**
 - OS: Fedora
 - OS Version: 31
 - Environment: Gnome
 - Application: Appimage
 - Application Version: PROD - Launcher 4.11.31 - Client 2.16.25

**Configuration**
 - The user is in input group ? YES
 - The environment uses Xorg ? YES
 - VA API detects H264 ? And H265 ? YES / NO

**To Reproduce**
1. Go to the launcher
2. Click on 'Start now'
3. The Stream launch
4. Everything freeze

**Additional context**
Similiar to this bug : https://github.com/NicolasGuilloux/blade-shadow-beta/issues/12

![Capture d’écran de 2020-02-14 17-31-42](https://user-images.githubusercontent.com/8980985/74553803-fcc4fb80-4f4f-11ea-8d1a-5bd369cd7deb.png)

The perl script gives me this [report](https://nicolasguilloux.eu/hostbin/129522943)
I got the exact same issue on another PC, Haswell aswell, on Fedora 30 : [report](https://nicolasguilloux.eu/hostbin/143139281)

In the linked bug, you said : 

> I will close this issue as it is solved. Nonetheless, if you still have the bug, send me your vainfo via Discord as your GPU may need to be added by Shadow on their whitelist.

Can it be the answer?

Also, I thought It might be the modifications aren't in production yet, but trying to install Beta or Alpha led me to this bug : https://github.com/NicolasGuilloux/blade-shadow-beta/issues/49

**Comment by aarnoud** [comment]
this issue has been fixed for most GPU, now as LIBVA is evolving or is different on some distributions, best is to use shadowcker : https://gitlab.com/aar642/shadowcker ```make alpha```
