### ISSUE TITLE
Issue with libva-intel-drive 2.4.0

### ISSUE THREAD

**Issue by mrwiwi** [NicolasGuilloux/blade-shadow-beta#52]
Just to let anyone know, if you're using an Intel HD Graphics card (Mine is the one integrated to an i5 4300u CPU on a thinkpad x240), you will have serious issues with that driver (Host System almost unresponsive, 1fps top...), solution is to downgrade it to 2.3.0 version, no issue at all again :)

**Comment by nrvx** [comment]
> Just to let anyone know, if you're using an Intel HD Graphics card (Mine is the one integrated to an i5 4300u CPU on a thinkpad x240), you will have serious issues with that driver (Host System almost unresponsive, 1fps top...), solution is to downgrade it to 2.3.0 version, no issue at all again :)

Thank you for your information, downgrading to 2.3.0 did the trick for my 4300m. :)

**Comment by mrwiwi** [comment]
For debiian, it's the i965-intel-driver version 2.3.0, for reference.

**Comment by mrwiwi** [comment]
> > Just to let anyone know, if you're using an Intel HD Graphics card (Mine is the one integrated to an i5 4300u CPU on a thinkpad x240), you will have serious issues with that driver (Host System almost unresponsive, 1fps top...), solution is to downgrade it to 2.3.0 version, no issue at all again :)
> 
> Thank you for your information, downgrading to 2.3.0 did the trick for my 4300m. :)

Just to know, did you succeed in making x265 stream working ? On windows it exit after a few seconds, on linux it's doesn't seems to work, even with hybrid driver for haswell.

**Comment by aarnoud** [comment]
does `vainfo`returns HEVC results ?

**Comment by mrwiwi** [comment]
> does `vainfo`returns HEVC results ?

Nope, only VP8 and h264... :(

**Comment by NicolasGuilloux** [comment]
Hello! Do you mind pasting the `vainfo` of both version so that we can compare please? Thanks :D

**Comment by nrvx** [comment]
I don't have any results for HEVC in `vainfo`, so I didn't even tried making an x265 stream working...

But, for your information, I'm not using the beta version because it's closing itself with a "unknown error" after a few minutes (error: L-100). _(I don't have any problem running the official .AppImage since I installed the beta and downgrade my drivers.)_

I don't know if it can be of any help, but here is the `vainfo` for my system. It is **exactly** the same for the 2.4.0 and 2.3.0 version:

> vainfo: VA-API version: 1.7 (libva 2.7.1)
> vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.3.0
> vainfo: Supported profile and entrypoints
>       VAProfileMPEG2Simple            : VAEntrypointVLD
>       VAProfileMPEG2Simple            : VAEntrypointEncSlice
>       VAProfileMPEG2Main              : VAEntrypointVLD
>       VAProfileMPEG2Main              : VAEntrypointEncSlice
>       VAProfileH264ConstrainedBaseline: VAEntrypointVLD
>       VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
>       VAProfileH264Main               : VAEntrypointVLD
>       VAProfileH264Main               : VAEntrypointEncSlice
>       VAProfileH264High               : VAEntrypointVLD
>       VAProfileH264High               : VAEntrypointEncSlice
>       VAProfileH264MultiviewHigh      : VAEntrypointVLD
>       VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
>       VAProfileH264StereoHigh         : VAEntrypointVLD
>       VAProfileH264StereoHigh         : VAEntrypointEncSlice
>       VAProfileVC1Simple              : VAEntrypointVLD
>       VAProfileVC1Main                : VAEntrypointVLD
>       VAProfileVC1Advanced            : VAEntrypointVLD
>       VAProfileNone                   : VAEntrypointVideoProc
>       VAProfileJPEGBaseline           : VAEntrypointVLD

> 
> vainfo: VA-API version: 1.7 (libva 2.7.1)
> vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.4.0
> vainfo: Supported profile and entrypoints
>       VAProfileMPEG2Simple            : VAEntrypointVLD
>       VAProfileMPEG2Simple            : VAEntrypointEncSlice
>       VAProfileMPEG2Main              : VAEntrypointVLD
>       VAProfileMPEG2Main              : VAEntrypointEncSlice
>       VAProfileH264ConstrainedBaseline: VAEntrypointVLD
>       VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
>       VAProfileH264Main               : VAEntrypointVLD
>       VAProfileH264Main               : VAEntrypointEncSlice
>       VAProfileH264High               : VAEntrypointVLD
>       VAProfileH264High               : VAEntrypointEncSlice
>       VAProfileH264MultiviewHigh      : VAEntrypointVLD
>       VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
>       VAProfileH264StereoHigh         : VAEntrypointVLD
>       VAProfileH264StereoHigh         : VAEntrypointEncSlice
>       VAProfileVC1Simple              : VAEntrypointVLD
>       VAProfileVC1Main                : VAEntrypointVLD
>       VAProfileVC1Advanced            : VAEntrypointVLD
>       VAProfileNone                   : VAEntrypointVideoProc
>       VAProfileJPEGBaseline           : VAEntrypointVLD
>

**Comment by aarnoud** [comment]
HEVC/H265 won't work if not supported and reported back by vainfo, x265 (as software decoding) isn't supported by Shadow only hardware. Don't worry about official appimage of Shadow, it's in fact a legacy version kept for compatibility until better solutions are found. The version to use on linux and that is being iterated on is Beta, and you should be able to also use Alpha.

**Comment by jbcayrou** [comment]
Hi,

I have the same issue on my Thinkpad X230 (on Arch Linux).
The shadow client did not work correctly with libva-intel-driver version 2.4 (the image returned is not clear and blocked, all the system freezes)
With libva-intel-driver in version 2.3.0 all work well !

**Workaround (Arch Linux) :**

Downgrade the version of libva-intel-driver
```
wget http://archlinux.arkena.net/archive/packages/l/libva-intel-driver/libva-intel-driver-2.3.0-2-x86_64.pkg.tar.xz
sudo pacman -U libva-intel-driver-2.3.0-2-x86_64.pkg.tar.xz  
```


**My Hardware**
* Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
* Intel HD Graphics 4000 

```
vainfo: VA-API version: 1.9 (libva 2.9.1)
vainfo: Driver version: Intel i965 driver for Intel(R) Ivybridge Mobile - 2.3.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD

```
