### ISSUE TITLE
Ubuntu 20.04 

### ISSUE THREAD

**Issue by syralk** [NicolasGuilloux/blade-shadow-beta#53]
the app image do not work on Ubuntu 20.04
I tried Alpha, Beta and the official release
Error is L-100

**Comment by aquadzn** [comment]
> the app image do not work on Ubuntu 20.04
> I tried Alpha, Beta and the official release
> Error is L-100

@syralk 

first enable the low configuration mode.
If you still have L-100 errors, try `sudo apt install intel-media-va-driver-non-free libva-glx2 && LIBVA_DRIVER_NAME=iHD ./Shadow.AppImage --no-sandbox`

**Comment by agentcobra** [comment]
@aquadzn lié à #48 ?

**Comment by syralk** [comment]
> > the app image do not work on Ubuntu 20.04
> > I tried Alpha, Beta and the official release
> > Error is L-100
> 
> @syralk
> 
> first enable the low configuration mode.
> If you still have L-100 errors, try `sudo apt install intel-media-va-driver-non-free libva-glx2 && LIBVA_DRIVER_NAME=iHD ./Shadow.AppImage --no-sandbox`

I switch to Manjaro 20
wokred great :)
I dont think I will go back to ubuntu lol

**Comment by aquadzn** [comment]
@agentcobra j'ai eu le même problème avec le menu rapide oui

**Comment by Shaltz** [comment]
@aquadzn

```
first enable the low configuration mode.
If you still have L-100 errors, try sudo apt install intel-media-va-driver-non-free libva-glx2 && LIBVA_DRIVER_NAME=iHD ./Shadow.AppImage --no-sandbox
```

Hi, thanks for the tip, it works ... I uess it s due to the  lack of proper intel driver...

**Comment by jamesweech** [comment]
Now it opens but I am getting this: 

Any ideas?


![Screenshot from 2020-05-06 00-40-02](https://user-images.githubusercontent.com/2097695/81126147-5bd45400-8f32-11ea-922c-b06abac5bafe.png)

**Comment by aarnoud** [comment]
@jamesweech ```allow_rgb10_configs=false ./ShadowBeta.AppImage```

**Comment by PowerMugen** [comment]
Hi, i'm having l-100 issue with shadowAlpha.appimage and ubuntu 20.04, the stream is fine I can use it sometimes for hours sometimes I only have L-100 errors in a row.
Stream is ok bug the alpha client quits often.
Cursor is locked, I have multi screens shadow client is on the main one.

Here's my config report https://nicolasguilloux.eu/hostbin/739552264

I prefer the Alpha app it's better and I have two computer one of them (on Zorin os) needs Alpha and I don't want to change to shadow everytime I change computers.

To gets the client to work properly I've use this command 
`sudo apt install intel-media-va-driver-non-free libva-glx2 && LIBVA_DRIVER_NAME=iHD ./ShadowAlpha.AppImage --no-sandbox
`


And I have change the /etc/drirc files for this one: 

`<driconf>
  <device driver="iris">
    <application name="Shadow" executable="Shadow">
      <option name="allow_rgb10_configs" value="false" />
    </application>
  </device>
</driconf>
`


Everythings runs fine excepts for almost random L-100 errors that can be annoying especialy during games when client quits during a fight !

**Comment by jamesweech** [comment]
@aarnoud I'm afraid even with that env variable setting set I get the same issue

**Comment by PowerMugen** [comment]
@jamesweech you could try changing the /etc/drirc file on your system (with sudo) and changing content I have found two examples on the discord, this one work on my ubuntu 20.04
```

<driconf>
  <device driver="iris">
    <application name="Shadow" executable="Shadow">
      <option name="allow_rgb10_configs" value="false" />
    </application>
  </device>  
</driconf>

```

or another example
```

<driconf>
  <device driver="iHD">
    <application name="Shadow" executable="Shadow">
      <option name="allow_rgb10_configs" value="false" />
    </application>
  </device>
  <device driver="intel">
    <application name="Shadow" executable="Shadow">
      <option name="allow_rgb10_configs" value="false" />
    </application>
  </device>  
</driconf>
```

**Comment by aarnoud** [comment]
disabling RGB10 on GPU that doesn't support it, is the only way to fix this reddish colour issue
