### ISSUE TITLE
Artefacts

### ISSUE THREAD

**Issue by Sok00** [NicolasGuilloux/blade-shadow-beta#56]
Decoding the stream does not work completely.
Picture at the Ende.
In AppImage-Stable work fine.

**System**
 - OS: 5.6.4-1-rt3-MANJARO #1 SMP PREEMPT_RT Thu Apr 16 18:54:16 UTC 2020 x86_64 GNU/Linux
 - Environment: Gnome
 - Application: AppImage and AUR

CPU
> 04: None 03.0: 10103 CPU
>   [Created at cpu.462]
>   Unique ID: [###]
>   Hardware Class: cpu
>   Arch: X86-64
>   Vendor: "GenuineIntel"
>   Model: 6.78.3 "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz"
>   Features: fpu,vme,de,pse,tsc,msr,pae,mce,cx8,apic,sep,mtrr,pge,mca,cmov,pat,pse36,clflush,dts,acpi,mmx,fxsr,sse,sse2,ss,ht,tm,pbe,syscall,nx,pdpe1gb,rdtscp,lm,constant_tsc,art,arch_perfmon,pebs,bts,rep_good,nopl,xtopology,nonstop_tsc,cpuid,aperfmperf,pni,pclmulqdq,dtes64,monitor,ds_cpl,vmx,est,tm2,ssse3,sdbg,fma,cx16,xtpr,pdcm,pcid,sse4_1,sse4_2,x2apic,movbe,popcnt,tsc_deadline_timer,aes,xsave,avx,f16c,rdrand,lahf_lm,abm,3dnowprefetch,cpuid_fault,epb,invpcid_single,pti,ssbd,ibrs,ibpb,stibp,tpr_shadow,vnmi,flexpriority,ept,vpid,ept_ad,fsgsbase,tsc_adjust,bmi1,avx2,smep,bmi2,erms,invpcid,mpx,rdseed,adx,smap,clflushopt,intel_pt,xsaveopt,xsavec,xgetbv1,xsaves,dtherm,ida,arat,pln,pts,hwp,hwp_notify,hwp_act_window,hwp_epp,md_clear,flush_l1d
>   Clock: 3000 MHz
>   BogoMips: 5202.65
>   Cache: 4096 kb
>   Units/Processor: 16
>   Config Status: cfg=new, avail=yes, need=no, active=unknown

SOUND:
> 14: PCI 1f.3: 0403 Audio device                                 
>   [Created at pci.386]
>   Unique ID: [###]
>   SysFS ID: /devices/pci0000:00/0000:00:1f.3
>   SysFS BusID: 0000:00:1f.3
>   Hardware Class: sound
>   Model: "Intel Sunrise Point-LP HD Audio"
>   Vendor: pci 0x8086 "Intel Corporation"
>   Device: pci 0x9d70 "Sunrise Point-LP HD Audio"
>   SubVendor: pci 0x1558 "CLEVO/KAPOK Computer"
>   SubDevice: pci 0x2422 
>   Revision: 0x21
>   Driver: "snd_hda_intel"
>   Driver Modules: "snd_hda_intel"
>   Memory Range: 0xdf320000-0xdf323fff (rw,non-prefetchable)
>   Memory Range: 0xdf300000-0xdf30ffff (rw,non-prefetchable)
>   IRQ: 137 (3593 events)
>   Module Alias: "[###]"
>   Driver Info #0:
>     Driver Status: snd_hda_intel is active
>     Driver Activation Cmd: "modprobe snd_hda_intel"
>   Config Status: cfg=new, avail=yes, need=no, active=unknown

GPU:
> 20: PCI 02.0: 0300 VGA compatible controller (VGA)              
>   [Created at pci.386]
>   Unique ID: [###]
>   SysFS ID: /devices/pci0000:00/0000:00:02.0
>   SysFS BusID: 0000:00:02.0
>   Hardware Class: graphics card
>   Model: "Intel Skylake GT2 [HD Graphics 520]"
>   Vendor: pci 0x8086 "Intel Corporation"
>   Device: pci 0x1916 "Skylake GT2 [HD Graphics 520]"
>   SubVendor: pci 0x1558 "CLEVO/KAPOK Computer"
>   SubDevice: pci 0x2425 
>   Revision: 0x07
>   Driver: "i915"
>   Driver Modules: "i915"
>   Memory Range: 0xde000000-0xdeffffff (rw,non-prefetchable)
>   Memory Range: 0xc0000000-0xcfffffff (ro,non-prefetchable)
>   I/O Ports: 0xf000-0xf03f (rw)
>   Memory Range: 0x000c0000-0x000dffff (rw,non-prefetchable,disabled)
>   IRQ: 135 (7168535 events)
>   Module Alias: "[###]"
>   Driver Info #0:
>     Driver Status: i915 is active
>     Driver Activation Cmd: "modprobe i915"
>   Config Status: cfg=new, avail=yes, need=no, active=unknown
> 
> Primary display adapter: #20 

APP:
> [daniel@daniel-n2425ju ~]$ pacman -Qi shadow-beta
> Name                     : shadow-beta
> Version                  : 5.0.557-1
> Beschreibung             : Shadow Bêta application
> Architektur              : x86_64
> URL                      : http://shadow.tech
> Lizenzen                 : unknown
> Gruppen                  : Nichts
> Stellt bereit            : shadow-beta
> Hängt ab von             : desktop-file-utils  freetype2  libuv  gconf  hicolor-icon-theme  json-c  libappindicator-gtk2  libbsd  libcurl-gnutls  libdrm  libnotify  libva  libxtst  nss  opus  qt5-base  qt5-svg
>                            sdl2  libcurl-compat  sdl  gcc7-libs  ttf-dejavu  libxss  libsndio-61-compat  gnome-keyring
> Optionale Abhängigkeiten : libva-vdpau-driver-shadow-nvidia: Patch for recent Nvidia GPU
>                            nouveau-fw: Driver for old Nvidia GPU [Installiert]
>                            libva-intel-driver: Driver for Intel GPU [Installiert]
> Benötigt von             : Nichts
> Optional für             : Nichts
> In Konflikt mit          : Nichts
> Ersetzt                  : Nichts
> Installationsgröße       : 429,32 MiB
> Packer                   : Unknown Packager
> Erstellt am              : Di 05 Mai 2020 09:46:36 CEST
> Installiert am           : Di 05 Mai 2020 09:46:54 CEST
> Installationsgrund       : Ausdrücklich installiert
> Installations-Skript     : Ja
> Verifiziert durch        : Nichts

**Configuration**

> X.Org X Server 1.20.8
> X Protocol Version 11, Revision 0
> Build Operating System: Linux Manjaro Linux
> Current Operating System: Linux daniel-n2425ju 5.6.4-1-rt3-MANJARO #1 SMP PREEMPT_RT Thu Apr 16 18:54:16 UTC 2020 x86_64
> Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.6-rt-x86_64 root=UUID=[######] rw quiet apparmor=1 security=apparmor udev.log_priority=3
> Build Date: 30 March 2020  06:33:12AM

> [daniel@daniel-n2425ju ~]$ vainfo
> vainfo: VA-API version: 1.7 (libva 2.7.1)
> vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
> vainfo: Supported profile and entrypoints
>       VAProfileNone                   :	VAEntrypointVideoProc
>       VAProfileNone                   :	VAEntrypointStats
>       VAProfileMPEG2Simple            :	VAEntrypointVLD
>       VAProfileMPEG2Simple            :	VAEntrypointEncSlice
>       VAProfileMPEG2Main              :	VAEntrypointVLD
>       VAProfileMPEG2Main              :	VAEntrypointEncSlice
>       VAProfileH264Main               :	VAEntrypointVLD
>       VAProfileH264Main               :	VAEntrypointEncSlice
>       VAProfileH264Main               :	VAEntrypointFEI
>       VAProfileH264Main               :	VAEntrypointEncSliceLP
>       VAProfileH264High               :	VAEntrypointVLD
>       VAProfileH264High               :	VAEntrypointEncSlice
>       VAProfileH264High               :	VAEntrypointFEI
>       VAProfileH264High               :	VAEntrypointEncSliceLP
>       VAProfileVC1Simple              :	VAEntrypointVLD
>       VAProfileVC1Main                :	VAEntrypointVLD
>       VAProfileVC1Advanced            :	VAEntrypointVLD
>       VAProfileJPEGBaseline           :	VAEntrypointVLD
>       VAProfileJPEGBaseline           :	VAEntrypointEncPicture
>       VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
>       VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
>       VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
>       VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
>       VAProfileVP8Version0_3          :	VAEntrypointVLD
>       VAProfileHEVCMain               :	VAEntrypointVLD
>       VAProfileHEVCMain               :	VAEntrypointEncSlice
>       VAProfileHEVCMain               :	VAEntrypointFEI

> [daniel@daniel-n2425ju ~]$ journalctl -b | grep -iE 'vdpau | dri driver'
> Mai 05 06:45:19 daniel-n2425ju /usr/lib/gdm-x-session[896]: (II) modeset(0): [DRI2]   DRI driver: iris
> Mai 05 06:45:19 daniel-n2425ju /usr/lib/gdm-x-session[896]: (II) modeset(0): [DRI2]   VDPAU driver: va_gl
> Mai 05 06:47:49 daniel-n2425ju /usr/lib/gdm-x-session[2657]: (II) modeset(0): [DRI2]   DRI driver: iris
> Mai 05 06:47:49 daniel-n2425ju /usr/lib/gdm-x-session[2657]: (II) modeset(0): [DRI2]   VDPAU driver: va_gl

Reproduce Error
Steps to reproduce:
1. Start Shadow beta
2. Login
3. Klick to Start

**Screenshots**
![Shadow_artefacts](https://user-images.githubusercontent.com/48594154/81050663-a7e6b080-8ec0-11ea-8ef3-2000cb6aaaa9.jpg)

**Comment by aarnoud** [comment]
```allow_rgb10_configs=false ./ShadowBeta.AppImage```

**Comment by Sok00** [comment]
Work :) thx
but if i resize the Window, make artefakts. (only on movement)
![Bildschirmfoto vom 2020-05-07 02-48-16](https://user-images.githubusercontent.com/48594154/81242486-90690e00-900d-11ea-8eb3-02fe3d16845c.jpg)

**Comment by aarnoud** [comment]
@Sok00 even in fullscreen ? with resolution in Shadow identical on your local Linux ?

**Comment by Sok00** [comment]
No only if i resize, for a very short time (Frames)
or if is not in Fullscreen then blinking randomly the black part (the empty part) of Straem.

I just wanted only to note it :)

**Comment by mrwiwi** [comment]
> `allow_rgb10_configs=false ./ShadowBeta.AppImage`

Is there a documentation of the differents options we can use with the appimage ?

**Comment by aarnoud** [comment]
those are not at all linked to Shadow or AppImage, it's Mesa parameters, you can find documentation in the Mesa source code :)

**Comment by mrwiwi** [comment]
> those are not at all linked to Shadow or AppImage, it's Mesa parameters, you can find documentation in the Mesa source code :)

Thanks ! 
Indeed ! Amazing how much you can learn on Linux with shadow ^^

**Comment by Sok00** [comment]
` hdr-compute-peak=no `

Is this helpful vor the "600" igpu/cpu ?

**Comment by kakawait** [comment]
`allow_rgb10_configs=false` works great. But is anyone I found solution for https://github.com/NicolasGuilloux/blade-shadow-beta/issues/56#issuecomment-624966423 ?

In full screen no issue, that why is not a big deal bug but good to fix if possible

**Comment by user28111999** [comment]
I'm having the same issue with Ubuntu and I also tried to use the Live OS

**Comment by NicolasGuilloux** [comment]
About the https://github.com/NicolasGuilloux/blade-shadow-beta/issues/56#issuecomment-624966423, the artefacts are supposed to be visible only on the black borders of the stream. I did not report this bug to the dev, I'll do it right now

**Comment by TheRealFanjin** [comment]
Any more solutions? It doesn't work for me when I do `allow_rgb10_configs=false ./Shadow.AppImage --no-sandbox`. It's still the same. Also, just a side question how do you exit Shadow when in fullscreen? Alt+tab doesn't work for me, I had to restart my computer :(

**Comment by Tethik** [comment]
> Any more solutions? It doesn't work for me when I do `allow_rgb10_configs=false ./Shadow.AppImage --no-sandbox`. It's still the same. Also, just a side question how do you exit Shadow when in fullscreen? Alt+tab doesn't work for me, I had to restart my computer :(

`Win+Alt+F` I believe toggles fullscreen. `Win+Alt+Q` exits the stream and returns you to the client.

This fix worked for me when the colours went all weird like the original post in the thread: 
https://nicolasguilloux.github.io/blade-shadow-beta/issues#the-drirc-fix

**Comment by TheRealFanjin** [comment]
> Win+Alt+F I believe toggles fullscreen. Win+Alt+Q exits the stream and returns you to the client.

I don't have the windows key, I'm using Linux on a Chromebook

> This fix worked for me when the colours went all weird like the original post in the thread:
>https://nicolasguilloux.github.io/blade-shadow-beta/issues#the-drirc-fix

I ran the command on the website but it still didn't do anything :(

**Comment by NicolasGuilloux** [comment]
@TheRealFanjin I let you open a new Issue about shortcuts and DRIRC on Chromebook since it is a specific case. It would be a lot better for the search as well, as people may find it easily. Make sure you mention this issue aswell please :)

Thanks folks!
