### ISSUE TITLE
App sits indefinitely at "Shadow is Ready" screen.

### ISSUE THREAD

**Issue by JesseDotEXE** [NicolasGuilloux/blade-shadow-beta#58]
**Describe the bug**
Shadow PC never starts, just sits at "Shadow is Ready" screen forever.

**System**
https://nicolasguilloux.eu/hostbin/2720221942

**Configuration**
Script from README returns successful.

**To Reproduce**
1. Launch Shadow.AppImage or ShadowBeta.AppImage
2. Start Shadow PC
3. While loading the issues occurs.

**Screenshots**
![image](https://user-images.githubusercontent.com/12961508/81376178-9e2f9980-90c8-11ea-976d-b104d520d793.png)

**Additional context**
New install of Ubuntu 20.04 any help would be greatly appreciated!

**Comment by aarnoud** [comment]
Hi, you need to configure VA for your system :

https://nicolasguilloux.github.io/blade-shadow-beta/#vainfo

**Comment by mrwiwi** [comment]
I had the same of using Wayland session btw...
Is it not compatible ?

**Comment by aarnoud** [comment]
Wayland is not compatible

**Comment by cubic3d** [comment]
Did cost me some time to find out, that it's not working on Wayland. Is there an ETA for Wayland?

**Comment by JesseDotEXE** [comment]
Got it working on my machine after setting up VA and some tinkering. It doesn't load like 1/4 of the time but a quick restart of the app seems to fix it.

**Comment by mrwiwi** [comment]
> Got it working on my machine after setting up VA and some tinkering. It doesn't load like 1/4 of the time but a quick restart of the app seems to fix it.

Hey, you mean you got it working ON Wayland ?
