### ISSUE TITLE
Stream flashes with H264 and hangs with H265

### ISSUE THREAD

**Issue by vtrubesset** [NicolasGuilloux/blade-shadow-beta#59]
Hello, first of all thank you for all the work around Shadow :)

**Describe the bug**
2 different behaviours, whether "Low bandwidth mode" is ticked or not in the Shadow options, which toggles H265 encoding. Same behaviours for each, whether "Fullscreen on start" is ticked or not.
 
- H264, "Low bandwidth mode" not ticked:
Stream hangs a few seconds on a black screen when starting, then flashes continuously and rapidly between a black screen and what is under the Shadow window (desktop, browser, ...)

- H265, "Low bandwidth mode" ticked:
Stream hangs a few seconds on a black screen when starting, then gets stuck on the first frame displaying the Shadow desktop, no visual feedback expect for the mouse movement and pointer.
Mouse input seems to work since the pointer changes when hovering different elements, and actions can be performed (open folder, right click, ...)

**System**
 - OS:
> Arch Linux
 - OS Version:
> 5.6.12-zen1-1-zen
 - Environment:
> Deepin
 - Application:
> shadow-beta
 - Application Version:
> 5.0.495-1 (latest)

**Configuration**
 - The user is in input group ?
> Yes
 - The environment uses Xorg ?
> Yes
 - VA API detects H264 ? And H265 ?
> See below
```
> curl https://raw.githubusercontent.com/NicolasGuilloux/blade-shadow-beta/master/scripts/check_driver.sh | bash
[...]
Found Arch.
Found vainfo.
H264 found.
H265 / HEVC found.

> vainfo
vainfo: VA-API version: 1.7 (libva 2.7.1)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.4.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
```

**Additional context**
- https://nicolasguilloux.eu/hostbin/2950202789
- `vainfo` output seems to be missing a few lines
- Discrepancy between `vainfo` & `check_script.sh` for H265 support 
- Similar behaviour than https://github.com/NicolasGuilloux/blade-shadow-beta/issues/13
- No issues with https://parsecgaming.com when used to check if inputs were registered
- ~~Deepin is a very fancy desktop environment so could it be related to a compositing issue?~~

Thanks for your help :)

EDIT: I just tried with compositing off, kind of the same behaviours:
- H264 hangs on a black screen, it's not flashing anymore
- H265 hangs on a black screen as well but with a green bar from left to right at mid height.
Shadow overlay is displayed though but I can't interact with it.
Mouse inputs still registered but no visual feedback.

**Comment by aarnoud** [comment]
Hey it seems your machine doesn't support H265, what's your CPU exact model ?

**Comment by vtrubesset** [comment]
Hi, its an i7-4600U, with 4400 igpu

**Comment by vtrubesset** [comment]
I tried with the alpha AppImage and still have the same issue
~~Also, shadowcker doesn't seem to start, see https://pastebin.com/4i6J51nH~~

EDIT: Shadowcker does start after running the `xhost +localhost ; xhost +local:docker` commands
