### ISSUE TITLE
No desktop icon in Gnome Shell

### ISSUE THREAD

**Issue by Jucgshu** [NicolasGuilloux/blade-shadow-beta#6]
Hi guys,

Been trying Shadow on Arch for the past 2 days or so, and it's working great. Only thing is that the desktop icon is not poping in Gnome Shell (Gnome 3.30).

I can see that the ```~/.local/share/applications/appimagekit-shadowbeta.desktop``` file is created, but I can't seem to find the Shadow icon in the user interface.

Thanks for your work.

-j

**Comment by NicolasGuilloux** [comment]
The icon on the launcher is bugged, but the shortcut should have an icon. Alex could fix it :)

**Comment by NicolasGuilloux** [comment]
After testing on a cleaned AntergOS computer, it appears that the icon requested is `appimagekit-shadowbeta` and it is located in the `~/.local/share/icons/hicolor/512x512/apps` folder.

It works well on this computer. Can you check your icons folder mentioned above please ?

**Comment by Jucgshu** [comment]
So I tried again with the new 2.0.1 Shadow version, deleted the ```~/.local/share/applications/appimagekit-shadowbeta.desktop``` file and relaunch Gnome Shell.

Still no Desktop icon when I type 'shadow' in the GShell.

The icon itself works well: I can open it without a problem from '~/.local/share/icons/hicolor/512x512/apps' but I can't find to launch the Shadow app directly from the Shell. Still have to run the script from the CLI.

-j

**Comment by NicolasGuilloux** [comment]
Oh I missunderstood. Yeap it's weird. Can you try to move the appimagekit-shadowbeta.desktop file to /usr/share/applications please ?

**Comment by Jucgshu** [comment]
Nope, still no luck.

**Comment by NicolasGuilloux** [comment]
Weird. So in your application launcher, there is no Shadow Beta.

It looks like a bug from GShell or you moved your file somewhere else so the .desktop file is pointing to the wrong location. Can you check that please ?

**Comment by aarnoud** [comment]
I'm thinking of a shortcut file format issue with some environments, that prevents file from being parsed correctly and displayed.

**Comment by Jucgshu** [comment]
So in the .desktop I can see ```TryExec=/home/userl/.local/share/Shadow\\sBeta/shadowbeta-linux-x86_64.AppImage```.

And the appimage file is located at ```~/.local/share/Shadow\ Beta/shadowbeta-linux-x86_64.AppImage```.

**Comment by NicolasGuilloux** [comment]
Hi!

Yes, it looks like the exec path is wrong. Can you correct is and restart your session please?

Did you edit the path once? Because it shouldn't be wrong. I tested again on a fresh installation and it was working.

**Comment by Notmarrco** [comment]
I had the same issue, and I solved it with the following .desktop file : 

```
Desktop Entry]                                                                                     
Name=shadowbeta                                                                                     
Comment=Shadow launcher                                                                             
Exec="/home/user1/.local/share/Shadow Beta/shadowbeta-linux-x86_64.AppImage" %U                    
Terminal=false                                                                                      
Type=Application                                                                                    
Icon=appimagekit-shadowbeta                                                                         
Categories=Network;                                                                                 
TryExec=/home/user1/.local/share/Shadow\sBeta/shadowbeta-linux-x86_64.AppImage                     
Actions=Uninstall;                                                                                  
                                                                                                    
X-Desktop-File-Install-Version=0.23                                                                 
X-AppImage-Comment=Generated by ./opt/shadowbeta/shadow-beta.wrapper                                
                                                                                                    
                                                                                                    
[Desktop Action Uninstall]                                                                          
Name=Remove desktop integration for shadowbeta                                                      
Exec="/home/user1/.local/share/Shadow Beta/shadowbeta-linux-x86_64.AppImage" --remove-appimage-desktop-integration
```

Note that you can validate your desktop file using : `desktop-file-validate ~/.local/share/applications/appimagekit-shadowbeta.desktop`. It showed me that : the uninstall action was not working (it searches for "[Desktop Action Uninstall]" instead of "[uninstall]").

Then it still didn't show up in gnome shell because of "TryExec" . At first the path was wrong, so I put the right path like @Jucgshu said, but it didn't work.

For a reason I can't explain it is waiting for a "\s" instead of "\ ", as shown in my example.

Not sure it's platform independant though... (i'm using ubuntu 18.10 and gnome shell 3.30)

**Comment by Notmarrco** [comment]
Note that I still have the issue that I don't see the icon when shadow is launched : 
![image](https://user-images.githubusercontent.com/1902611/51030338-662e4a00-1599-11e9-9cdb-8266736bef90.png)
(top icon is the desktop file from previous post - to launch shadow -, and bottom icon is the icon of the _running_ Shadow :thinking: )
Should I open a new issue or do you think it's related ?

**Comment by aarnoud** [comment]
Hi, thanks for feedback, I was sure it was some parsing issue on some DE... I'll check if we can do something for that, as desktop link is being generated by https://github.com/simoniz0r/deb2appimage scripts.

Regarding secondary icon, nothing we can do for now, as this process is forked by Shadow Launcher and doesn't come it seems with an icon, you should open a new issue please for dev to look at this.

**Comment by aarnoud** [comment]
https://github.com/simoniz0r/deb2appimage/blob/0aa7ea71ebd2361b9dac957bcc64c9d6cb093778/resources/desktopintegration#L263

&

https://github.com/simoniz0r/deb2appimage/blob/0aa7ea71ebd2361b9dac957bcc64c9d6cb093778/resources/desktopintegration#L240

for later processing :)

**Comment by NicolasGuilloux** [comment]
Hi everyone !

About the icon in the taskbar (or dock), it is an application issue. Actually even when I use the `.deb` file, I have this issue.
It is not related to the AppImage so.

So I would like to know if we were talking about the Icon in the applications launcher or the icon in the fock when the launcher is started.

**Comment by aarnoud** [comment]
next upcoming Blade release no longer includes any spaces in the path to the binary :)
