### ISSUE TITLE
L-100 (shadow:2434): libnotify-WARNING  Failed to connect to proxy

### ISSUE THREAD

**Issue by Thomatorius** [NicolasGuilloux/blade-shadow-beta#60]
**Describe the bug**
If i try to start streaming the launcher shows error-code L-100.

I started from Terminal and there is thrown a Warning eg failed to connect to proxy.

I already tried both options stable/speed. I also checkt lan and wlan. All time the same error.

System:

Ubuntu 20.04 LTS

Shadow: AppImage

is this a known issue or can anyone help me?

**Comment by aarnoud** [comment]
please fill the bug issues with all the requested details
