### ISSUE TITLE
Missing dependency in check_driver.sh for Intel Graphics on 20.04

### ISSUE THREAD

**Issue by bradloh** [NicolasGuilloux/blade-shadow-beta#62]
**Describe the bug**
20.04 running on integrated Intel graphics appears to require the intel-media-va-driver-non-free package, but this is not addressed by the script.

**System**
 - OS: Ubuntu
 - OS Version: 20.04
 - Environment: Gnome
 - Application: AppImage
 - Application Version: 4.14.16

**Configuration**
 - The user is in input group: yes
 - The environment uses Xorg: yes
 - VA API detects H264 ? And H265: yes

**To Reproduce**
1. Install 20.04 on an Intel CPU with no discrete graphics (integrated only)
2. Run the scripts in this repo
3. Try to launch Shadow
4. See error L-100

**Workaround**
sudo apt install intel-media-va-driver-non-free

**Comment by prhod** [comment]
I had the same issue, and the workaroud fix it ! (thanks @bradloh ).
If it can help to fix the issue, here is my system report https://nicolasguilloux.eu/hostbin/564211515

**Comment by aarnoud** [comment]
hehe glad you got it work, it's not a workaround, but package required to install on 20.04, it's unrelated to shadow but the linux VAAPI drivers required :p

**Comment by prhod** [comment]
Hi @aarnoud I see you closed this issue. Could this check be added to the check_driver.sh as stated in this issue ? It could help other to troubleshoot this problem (my future self is one of them ! :p )
