### ISSUE TITLE
Problems connecting Video to shadow

### ISSUE THREAD

**Issue by chroeseler** [NicolasGuilloux/blade-shadow-beta#7]
Hi,
i run blade-shadow- beta on an arch linux:

> x220 4.18.12-arch1-1-ARCH x86_64 GNU/Linux

The app is running, but when I try to connect to the blade server I find a Windows PC/Blade but by connecting the video, the app gives me

> An unknown Error occured

The second time I try to connect the shell gives me

> (node:4140) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: kill ESRCH
(node:4140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'm still trying to figure out whats happening, but would appreciate every help. 

Vg Chris

**Comment by NicolasGuilloux** [comment]
Hi !

Did you use the AppImage available on the [website](https://nicolasguilloux.github.io/blade-shadow-beta/#appimage) ? 
There are a few thing to do before using Shadow on Linux like checking if you use X11, and put your user in the `input` group.

Did you also check your VA-API drivers ?

**Comment by chroeseler** [comment]
Hi,
yes I use the AppImage and my user is in th einput group.

I did check VA-API drivers. 

vainfo: VA-API version: 1.3 (libva 2.3.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Sandybridge Mobile - 2.2.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc


Last but not least I use X11 with awesome WM.

name of display:    :0
version number:    11.0
vendor string:    The X.Org Foundation
vendor release number:    12001000
X.Org version: 1.20.1
maximum request size:  16777212 bytes
motion buffer size:  256
bitmap unit, bit order, padding:    32, LSBFirst, 32
image byte order:    LSBFirst
number of supported pixmap formats:    7
supported pixmap formats:
    depth 1, bits_per_pixel 1, scanline_pad 32
    depth 4, bits_per_pixel 8, scanline_pad 32
    depth 8, bits_per_pixel 8, scanline_pad 32
    depth 15, bits_per_pixel 16, scanline_pad 32
    depth 16, bits_per_pixel 16, scanline_pad 32
    depth 24, bits_per_pixel 32, scanline_pad 32
    depth 32, bits_per_pixel 32, scanline_pad 32
keycode range:    minimum 8, maximum 255
focus:  window 0x2400022, revert to Parent
number of extensions:    28
    BIG-REQUESTS
    Composite
    DAMAGE
    DOUBLE-BUFFER
    DPMS
    DRI2
    DRI3
    GLX
    Generic Event Extension
    MIT-SCREEN-SAVER
    MIT-SHM
    Present
    RANDR
    RECORD
    RENDER
    SECURITY
    SHAPE
    SYNC
    X-Resource
    XC-MISC
    XFIXES
    XFree86-DGA
    XFree86-VidModeExtension
    XINERAMA
    XInputExtension
    XKEYBOARD
    XTEST
    XVideo
default screen number:    0
number of screens:    1


But I noticed that shadow cannot detect if I'm using X11.
`WARNING:
 • Impossible to check if you are on Xorg or not.
`
I overlooked it as it is just a warning and the client is still starting.

Also this are messages I get on terminal while using the AppImage. 
** Message: 21:24:35.202: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files

(node:1310) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The name org.freedesktop.secrets was not provided by any .service files

(node:1310) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:1310) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: kill ESRCH

Vg Chris

**Comment by NicolasGuilloux** [comment]
Hi Chris!

You forgot to mention the distribution :p

Can you also use the parameter `--report` when launching the AppImage and send back the link?

**Comment by chroeseler** [comment]
Good point!
x220 4.18.12-arch1-1-ARCH x86_64 GNU/Linux

Interesting, when I start the AppImage with --report I get 
`Empty file !`

Also we can ignore the environnement warning. Was some bad configuration on my side.

**Comment by NicolasGuilloux** [comment]
Okay so for the node Warnings, everybody get this. It will not block anything.

Did you installed it from AUR?

Can you do `ldd` on the binary? It's located in /opt/shadowbeta/resources/app.asar.unpacked/Icantrememberthefolders/Shadow.

Sorry I'm on my phone :x

**Comment by chroeseler** [comment]
No, I got It from github.io.
I have the AppImage just laying around in some folder.

**Comment by chroeseler** [comment]
Hey, got one step further.
Some dependencies were absence. Now report gives. 
"[https://nicolasguilloux.eu/hostbin/2437752781](https://nicolasguilloux.eu/hostbin/2437752781)"

**Comment by NicolasGuilloux** [comment]
You use an old AppImage, the current version is 2.0.2. Can you upgrade it and try again please?

**Comment by chroeseler** [comment]
Ouch! This sure helped. 
It could have been so simple... ^^
Thank you very much. Time to play! 
Vg
