### ISSUE TITLE
Display with wrong colors

### ISSUE THREAD

**Issue by prhod** [NicolasGuilloux/blade-shadow-beta#70]
**Describe the bug**
Last week, I had no trouble with Shadow. The client updated, and was not able to connect anymore to the remote server (R-0x7F error). 
Checking the requirements on Ubuntu (I'm using 20.04) on https://help.shadow.tech/hc/en-gb/articles/360015561600-Hardware-Requirements-For-Using-Shadow, I saw the optionnal requirement of libva-glx2.
I've installed it and then managed to get connected.
 But the image is now not usable anymore: 
![Capture d’écran du 2020-09-02 18-10-13](https://user-images.githubusercontent.com/5628909/92009247-86031a80-ed48-11ea-8e54-2d966e4c961d.png)

It was with Stable Shadow.AppImage. I then tried the ShadowBeta.AppImage, but I have the same issue.
System is up-to-date.

I've checked with an other PC on WIndows without issue, It could be a problem with my Ubuntu set-up, but it was functional last week before the update. 

**System**
 - OS: Ubuntu
 - OS Version: 20.04
 - Environment: Gnome and i3 (checked with both)
 - Application: ShadowBeta.AppImage
 - Application Version: 4.16.6

**Configuration**
 - The user is in input group ? _no, it wasn't needed until now_
 - The environment uses Xorg ? _I think so (with gnome and i3)_
 - VA API detects H264 ? And H265 ? _yes (check_driver.sh scripts reports no error)_

**To Reproduce**
Logging to Shadow and see screen

**Screenshots**
added in the description

**Additional context**

**Comment by aarnoud** [comment]
check https://nicolasguilloux.github.io/blade-shadow-beta/issues#the-drirc-fix

**Comment by prhod** [comment]
thanks for the solution :pray: and sorry for opening a not relevant issue !
