### ISSUE TITLE
Will not run on VMWare/Ubuntu 18.04 LTS guest

### ISSUE THREAD

**Issue by jreichert** [NicolasGuilloux/blade-shadow-beta#71]
**Describe the bug**
Shadow client will not run on a VMWare Fusion installation with an Ubuntu 18.04 LTS guest.  I have not tried this on Workstation but suspect the same problem may occur in that environment as well.

**System**
 - OS: Ubuntu
 - OS Version: 18.04
 - Environment: Gnome
 - Application: AppImage
 - Application Version: 3.3.17

**Configuration**
 - The user is in input group ? yes
 - The environment uses Xorg ? yes
 - VA API detects H264 ? And H265 ? can't tell (can't get to this step)

**To Reproduce**
* Run the Shadow Launcher
* The initial launch screen comes up as expected with "starting Shadow"
* Displays "Shadow is Ready" with the orange "Start Now" button
* Click the button
* Streaming does not start, receive "Error Code: R-0x4"
* However, I have verified that the remote Shadow VM started as expected as I'm able to connect to it from Parsec or Steam Remote Play.

**Screenshots**

**Additional context**
I don't know much about Linux graphics drivers, but this may not be a solvable issue.  I have ensured that I have all the required dependencies installed.  However, I get this when I run `vainfo`:

libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/vmwgfx_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

I'm assuming this means that the `vmwgfx` video driver for VMWare doesn't support the API signatures expected by VA-API.  A brief Google search didn't turn of any explicit confirmation of whether or not the driver provides this support. I tried to force the use of the i965 driver with `export LIBVA_DRIVER_NAME=i965` in my .bashrc, but the `vainfo` just gave me this:

libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'i965'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
vainfo: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
Aborted (core dumped)

If there's some clever solution here I can't think of then great; otherwise, this should probably go on the "known issues" page.

**Comment by aarnoud** [comment]
shadow requires a direct access to an hardware decoder, means it could only work on a VM with a GPU passthrough.
