### ISSUE TITLE
20 FPS from the client

### ISSUE THREAD

**Issue by changemenemo** [NicolasGuilloux/blade-shadow-beta#73]
**Describe the bug**
I got 20 FPS from time to time. 
I don't think it's an external app, it would happen each time since I have always the same apps opened. But it might be.
In normal time I got 60 FPS. 
The vsync that you see on the photo is always active so that can't be it.
I didn't pinpoint the exact origin of this problem. Not sure that it is display safe option from the client.

The FPS counter is from cuda installation but I can totally confirm there is a drop a frame visually. 
It is the official app image, didn't try the beta yet. 
**System**
 - OS: fedora
 - OS Version: 32
 - Environment: Gnome
 - Application: AppImage extracted due to r1 bug
 - Application Version: 5.0.709

**Configuration**
 - The user is in input group ? Not sure yet will check
 - The environment uses Xorg ? Xorg with nvidia cuda
 - VA API detects H264 ? And H265 ? Everything should work, will check after 
1080Ti

**To Reproduce**
Not sure yet
**Screenshots**
![image](https://user-images.githubusercontent.com/9523075/92493363-b6d5ca80-f1f4-11ea-8f4a-1ea0c9f59894.jpeg)

**Comment by NicolasGuilloux** [comment]
Hi! The 140 indicator is from the Shadow itself (Windows side) and the 20 fps is from the client side (Linux), right? Do you have a tool to check the CPU and GPU load?

**Comment by changemenemo** [comment]
The 140 is from the Ubisoft or uplay on the shadow.
The 20 is from Linux client side 
And it was not related to gpu load or cpu load at all. It varies simply by sliding a little bit the option in the launcher and put it back in place even

**Comment by NicolasGuilloux** [comment]
How long does the framerate drop is effective? Is it a small or a long drop?

**Comment by NicolasGuilloux** [comment]
Closed due to inactivity
