### ISSUE TITLE
Not respecting bandwidth limitation

### ISSUE THREAD

**Issue by changemenemo** [NicolasGuilloux/blade-shadow-beta#75]
**Describe the bug**
It doesn't respect the limit I put in the client and so I have a lot of dropped frames because of my QOS I put in place to avoid exactly the overreach of the frames 

**System**
 - OS: fedora
 - OS Version: 32
 - Environment: gnome
 - Application: app image extracted
 - Application Version: 5.0.709

**Configuration**
 - The user is in input group ? Don t know
 - The environment uses Xorg ? Yes
 - VA API detects H264 ? And H265 ? Both normally 

```
VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG4Simple            : VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    : VAEntrypointVLD
      <unknown profile>               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
```
1080Ti

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/9523075/92793433-ab2e0380-f3ae-11ea-975b-3902dc8e655b.jpeg)

**Additional context**

**Comment by NicolasGuilloux** [comment]
@boistordu A big clean has be done since your issue, do you mind checking if you experience the same issue please?

**Comment by changemenemo** [comment]
I will do some extending testing soon to see if by touching nothing I still encounter the same problem. And of course I m pretty sure that the result will be different among Ubuntu and fedora. I can test on fedora 33. I will try after that a run on Ubuntu when the specific host is ready for that

**Comment by NicolasGuilloux** [comment]
Did you try with the latest version? Since the issue is pretty old, and a lot of updates came inbetwee, maybe this issue is outdated.

I close it for inactivity, but if you can open it back if you want;
