### ISSUE TITLE
Keyboard issue on mac.

### ISSUE THREAD

**Issue by WumpusBackup** [NicolasGuilloux/blade-shadow-beta#81]
Hey so my shadow has worked always in the past, my mouse works perfectly fine i can click everything but my keyboard decides to just not work. It's a standard apple keyboard. I've already tried installing the drivers but this did not change anything. Any way to fix this?

**Comment by NicolasGuilloux** [comment]
Hi there! Without any additional information, we can't help you.

Do you mind following the [template](https://github.com/NicolasGuilloux/blade-shadow-beta/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)  that help us gather enough information to help you?

**Comment by NicolasGuilloux** [comment]
Closed for inactivity
