### ISSUE TITLE
L-104 when connecting

### ISSUE THREAD

**Issue by calibrae** [NicolasGuilloux/blade-shadow-beta#84]
Hi, 

Using Fedora 33, with Gnome/xorg on a 2015 macbook air 13'
I installed dependencies, tried the check_driver.sh, all good.

✅ Found Fedora.
✅ Found vainfo.

✅ H264 found.
✅ H265 / HEVC found.

I had to unpack the appImage to run the binary directy, and I finally got to the "connecting to shadow"
But after a while it goes back to the main screen with a 
L-104 Sorry, an issue happened when receiving the stream
Turn off your shadow... yadda yadda.

I tried shadowcker as well (which I would really like NOT to use since I hate this docker everywhere trend) and it fails with exactly the same problem.
Stable and beta are failing in the same way.
Of course, the shadow client is working on macos. 

Any help would be greatly appreciated.

**Comment by calibrae** [comment]
Apparently, it was a problem on Blade side.
Solved it with a fresh fedora install and all necessary packages, and the app image extract.
Thanks.

**Comment by NicolasGuilloux** [comment]
I would guess it is also linked to this issue : https://github.com/NicolasGuilloux/blade-shadow-beta/issues/80#issuecomment-748417866
