### ISSUE TITLE
AppImage is incomplete

### ISSUE THREAD

**Issue by Arignir** [NicolasGuilloux/blade-shadow-beta#9]
Hello,

The provided AppImage doesn't contain all needed libraries. The list is long, but for example, `libcurl` has a dependency over `libkrb`, `libkrb5crypto`, `libkrb5support` etc. which are either not provided or at the wrong version.

An easy way to know which librairies are missing is to run `lld` against **all binaries and libraries of the image**, and ensure it never returns `not found` in the given requirement **and** it never uses the host's libraries (all paths should be relative to the image's root).

Cordially,

**Comment by NicolasGuilloux** [comment]
Hi !

It's possible. Alex manages the libraries embeded in the AppImage as I do not know anything about AppImage :p 
I let him manager this issue.

**Comment by Arignir** [comment]
Up, any news?

**Comment by aarnoud** [comment]
Hi, could you please try this build and tell me if it's fixed for you, also can you give more details on your distribution : 

https://gitlab.com/aar642/shadow-appimage/-/jobs/114041227/artifacts/raw/shadowbeta-linux-x86_64.AppImage

thanks,

Alex^
